package cef;
import cef.CefLibrary._cef_frame_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_display_handler_capi.h:17</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_display_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_address_change_callback* */
	public cef_display_handler_t.on_address_change_callback on_address_change;
	/** C type : on_title_change_callback* */
	public cef_display_handler_t.on_title_change_callback on_title_change;
	/** C type : on_favicon_urlchange_callback* */
	public cef_display_handler_t.on_favicon_urlchange_callback on_favicon_urlchange;
	/** C type : on_fullscreen_mode_change_callback* */
	public cef_display_handler_t.on_fullscreen_mode_change_callback on_fullscreen_mode_change;
	/** C type : on_tooltip_callback* */
	public cef_display_handler_t.on_tooltip_callback on_tooltip;
	/** C type : on_status_message_callback* */
	public cef_display_handler_t.on_status_message_callback on_status_message;
	/** C type : on_console_message_callback* */
	public cef_display_handler_t.on_console_message_callback on_console_message;
	/** <i>native declaration : include\capi\cef_display_handler_capi.h:10</i> */
	public interface on_address_change_callback extends Callback {
		void apply(cef_display_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_string_utf16_t url);
	};
	/** <i>native declaration : include\capi\cef_display_handler_capi.h:11</i> */
	public interface on_title_change_callback extends Callback {
		void apply(cef_display_handler_t self, cef_browser_t browser, cef_string_utf16_t title);
	};
	/** <i>native declaration : include\capi\cef_display_handler_capi.h:12</i> */
	public interface on_favicon_urlchange_callback extends Callback {
		void apply(cef_display_handler_t self, cef_browser_t browser, Pointer icon_urls);
	};
	/** <i>native declaration : include\capi\cef_display_handler_capi.h:13</i> */
	public interface on_fullscreen_mode_change_callback extends Callback {
		void apply(cef_display_handler_t self, cef_browser_t browser, int fullscreen);
	};
	/** <i>native declaration : include\capi\cef_display_handler_capi.h:14</i> */
	public interface on_tooltip_callback extends Callback {
		int apply(cef_display_handler_t self, cef_browser_t browser, cef_string_utf16_t text);
	};
	/** <i>native declaration : include\capi\cef_display_handler_capi.h:15</i> */
	public interface on_status_message_callback extends Callback {
		void apply(cef_display_handler_t self, cef_browser_t browser, cef_string_utf16_t value);
	};
	/** <i>native declaration : include\capi\cef_display_handler_capi.h:16</i> */
	public interface on_console_message_callback extends Callback {
		int apply(cef_display_handler_t self, cef_browser_t browser, cef_string_utf16_t message, cef_string_utf16_t source, int line);
	};
	public cef_display_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_address_change", "on_title_change", "on_favicon_urlchange", "on_fullscreen_mode_change", "on_tooltip", "on_status_message", "on_console_message");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_address_change C type : on_address_change_callback*<br>
	 * @param on_title_change C type : on_title_change_callback*<br>
	 * @param on_favicon_urlchange C type : on_favicon_urlchange_callback*<br>
	 * @param on_fullscreen_mode_change C type : on_fullscreen_mode_change_callback*<br>
	 * @param on_tooltip C type : on_tooltip_callback*<br>
	 * @param on_status_message C type : on_status_message_callback*<br>
	 * @param on_console_message C type : on_console_message_callback*
	 */
	public cef_display_handler_t(cef_base_t base, cef_display_handler_t.on_address_change_callback on_address_change, cef_display_handler_t.on_title_change_callback on_title_change, cef_display_handler_t.on_favicon_urlchange_callback on_favicon_urlchange, cef_display_handler_t.on_fullscreen_mode_change_callback on_fullscreen_mode_change, cef_display_handler_t.on_tooltip_callback on_tooltip, cef_display_handler_t.on_status_message_callback on_status_message, cef_display_handler_t.on_console_message_callback on_console_message) {
		super();
		this.base = base;
		this.on_address_change = on_address_change;
		this.on_title_change = on_title_change;
		this.on_favicon_urlchange = on_favicon_urlchange;
		this.on_fullscreen_mode_change = on_fullscreen_mode_change;
		this.on_tooltip = on_tooltip;
		this.on_status_message = on_status_message;
		this.on_console_message = on_console_message;
	}
	public cef_display_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_display_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_display_handler_t implements Structure.ByValue {
		
	};
}
