package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:103</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_urlparts_t extends Structure {
	/** C type : cef_string_t */
	public cef_string_utf16_t spec;
	/** C type : cef_string_t */
	public cef_string_utf16_t scheme;
	/** C type : cef_string_t */
	public cef_string_utf16_t username;
	/** C type : cef_string_t */
	public cef_string_utf16_t password;
	/** C type : cef_string_t */
	public cef_string_utf16_t host;
	/** C type : cef_string_t */
	public cef_string_utf16_t port;
	/** C type : cef_string_t */
	public cef_string_utf16_t origin;
	/** C type : cef_string_t */
	public cef_string_utf16_t path;
	/** C type : cef_string_t */
	public cef_string_utf16_t query;
	public cef_urlparts_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("spec", "scheme", "username", "password", "host", "port", "origin", "path", "query");
	}
	/**
	 * @param spec C type : cef_string_t<br>
	 * @param scheme C type : cef_string_t<br>
	 * @param username C type : cef_string_t<br>
	 * @param password C type : cef_string_t<br>
	 * @param host C type : cef_string_t<br>
	 * @param port C type : cef_string_t<br>
	 * @param origin C type : cef_string_t<br>
	 * @param path C type : cef_string_t<br>
	 * @param query C type : cef_string_t
	 */
	public cef_urlparts_t(cef_string_utf16_t spec, cef_string_utf16_t scheme, cef_string_utf16_t username, cef_string_utf16_t password, cef_string_utf16_t host, cef_string_utf16_t port, cef_string_utf16_t origin, cef_string_utf16_t path, cef_string_utf16_t query) {
		super();
		this.spec = spec;
		this.scheme = scheme;
		this.username = username;
		this.password = password;
		this.host = host;
		this.port = port;
		this.origin = origin;
		this.path = path;
		this.query = query;
	}
	public cef_urlparts_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_urlparts_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_urlparts_t implements Structure.ByValue {
		
	};
}
