package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_geolocation_handler_capi.h:12</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_geolocation_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_request_geolocation_permission_callback* */
	public cef_geolocation_handler_t.on_request_geolocation_permission_callback on_request_geolocation_permission;
	/** C type : on_cancel_geolocation_permission_callback* */
	public cef_geolocation_handler_t.on_cancel_geolocation_permission_callback on_cancel_geolocation_permission;
	/** <i>native declaration : include\capi\cef_geolocation_handler_capi.h:10</i> */
	public interface on_request_geolocation_permission_callback extends Callback {
		int apply(cef_geolocation_handler_t self, cef_browser_t browser, cef_string_utf16_t requesting_url, int request_id, cef_geolocation_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_geolocation_handler_capi.h:11</i> */
	public interface on_cancel_geolocation_permission_callback extends Callback {
		void apply(cef_geolocation_handler_t self, cef_browser_t browser, int request_id);
	};
	public cef_geolocation_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_request_geolocation_permission", "on_cancel_geolocation_permission");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_request_geolocation_permission C type : on_request_geolocation_permission_callback*<br>
	 * @param on_cancel_geolocation_permission C type : on_cancel_geolocation_permission_callback*
	 */
	public cef_geolocation_handler_t(cef_base_t base, cef_geolocation_handler_t.on_request_geolocation_permission_callback on_request_geolocation_permission, cef_geolocation_handler_t.on_cancel_geolocation_permission_callback on_cancel_geolocation_permission) {
		super();
		this.base = base;
		this.on_request_geolocation_permission = on_request_geolocation_permission;
		this.on_cancel_geolocation_permission = on_cancel_geolocation_permission;
	}
	public cef_geolocation_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_geolocation_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_geolocation_handler_t implements Structure.ByValue {
		
	};
}
