package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_dialog_handler_capi.h:12</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_dialog_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_file_dialog_callback* */
	public cef_dialog_handler_t.on_file_dialog_callback on_file_dialog;
	/** <i>native declaration : include\capi\cef_dialog_handler_capi.h:11</i> */
	public interface on_file_dialog_callback extends Callback {
		int apply(cef_dialog_handler_t self, cef_browser_t browser, int mode, cef_string_utf16_t title, cef_string_utf16_t default_file_path, Pointer accept_filters, int selected_accept_filter, cef_file_dialog_callback_t callback);
	};
	public cef_dialog_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_file_dialog");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_file_dialog C type : on_file_dialog_callback*
	 */
	public cef_dialog_handler_t(cef_base_t base, cef_dialog_handler_t.on_file_dialog_callback on_file_dialog) {
		super();
		this.base = base;
		this.on_file_dialog = on_file_dialog;
	}
	public cef_dialog_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_dialog_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_dialog_handler_t implements Structure.ByValue {
		
	};
}
