package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_web_plugin_capi.h:16</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_web_plugin_info_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** <i>native declaration : include\capi\cef_web_plugin_capi.h:12</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_web_plugin_info_t self);
	};
	/** <i>native declaration : include\capi\cef_web_plugin_capi.h:13</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_web_plugin_info_t self);
	};
	/** <i>native declaration : include\capi\cef_web_plugin_capi.h:14</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_web_plugin_info_t self);
	};
	/** <i>native declaration : include\capi\cef_web_plugin_capi.h:15</i> */
	public interface cef_string_userfree_t_callback4 extends Callback {
		int apply(cef_web_plugin_info_t self);
	};
	public cef_web_plugin_info_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base");
	}
	/** @param base C type : cef_base_t */
	public cef_web_plugin_info_t(cef_base_t base) {
		super();
		this.base = base;
	}
	public cef_web_plugin_info_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_web_plugin_info_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_web_plugin_info_t implements Structure.ByValue {
		
	};
}
