package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_scheme_capi.h:6</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_scheme_registrar_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : add_custom_scheme_callback* */
	public cef_scheme_registrar_t.add_custom_scheme_callback add_custom_scheme;
	/** <i>native declaration : include\capi\cef_scheme_capi.h:5</i> */
	public interface add_custom_scheme_callback extends Callback {
		int apply(cef_scheme_registrar_t self, cef_string_utf16_t scheme_name, int is_standard, int is_local, int is_display_isolated);
	};
	public cef_scheme_registrar_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "add_custom_scheme");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param add_custom_scheme C type : add_custom_scheme_callback*
	 */
	public cef_scheme_registrar_t(cef_base_t base, cef_scheme_registrar_t.add_custom_scheme_callback add_custom_scheme) {
		super();
		this.base = base;
		this.add_custom_scheme = add_custom_scheme;
	}
	public cef_scheme_registrar_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_scheme_registrar_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_scheme_registrar_t implements Structure.ByValue {
		
	};
}
