package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_jsdialog_handler_capi.h:16</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_jsdialog_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_jsdialog_callback* */
	public cef_jsdialog_handler_t.on_jsdialog_callback on_jsdialog;
	/** C type : on_before_unload_dialog_callback* */
	public cef_jsdialog_handler_t.on_before_unload_dialog_callback on_before_unload_dialog;
	/** C type : on_reset_dialog_state_callback* */
	public cef_jsdialog_handler_t.on_reset_dialog_state_callback on_reset_dialog_state;
	/** C type : on_dialog_closed_callback* */
	public cef_jsdialog_handler_t.on_dialog_closed_callback on_dialog_closed;
	/** <i>native declaration : include\capi\cef_jsdialog_handler_capi.h:12</i> */
	public interface on_jsdialog_callback extends Callback {
		int apply(cef_jsdialog_handler_t self, cef_browser_t browser, cef_string_utf16_t origin_url, int dialog_type, cef_string_utf16_t message_text, cef_string_utf16_t default_prompt_text, cef_jsdialog_callback_t callback, IntByReference suppress_message);
	};
	/** <i>native declaration : include\capi\cef_jsdialog_handler_capi.h:13</i> */
	public interface on_before_unload_dialog_callback extends Callback {
		int apply(cef_jsdialog_handler_t self, cef_browser_t browser, cef_string_utf16_t message_text, int is_reload, cef_jsdialog_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_jsdialog_handler_capi.h:14</i> */
	public interface on_reset_dialog_state_callback extends Callback {
		void apply(cef_jsdialog_handler_t self, cef_browser_t browser);
	};
	/** <i>native declaration : include\capi\cef_jsdialog_handler_capi.h:15</i> */
	public interface on_dialog_closed_callback extends Callback {
		void apply(cef_jsdialog_handler_t self, cef_browser_t browser);
	};
	public cef_jsdialog_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_jsdialog", "on_before_unload_dialog", "on_reset_dialog_state", "on_dialog_closed");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_jsdialog C type : on_jsdialog_callback*<br>
	 * @param on_before_unload_dialog C type : on_before_unload_dialog_callback*<br>
	 * @param on_reset_dialog_state C type : on_reset_dialog_state_callback*<br>
	 * @param on_dialog_closed C type : on_dialog_closed_callback*
	 */
	public cef_jsdialog_handler_t(cef_base_t base, cef_jsdialog_handler_t.on_jsdialog_callback on_jsdialog, cef_jsdialog_handler_t.on_before_unload_dialog_callback on_before_unload_dialog, cef_jsdialog_handler_t.on_reset_dialog_state_callback on_reset_dialog_state, cef_jsdialog_handler_t.on_dialog_closed_callback on_dialog_closed) {
		super();
		this.base = base;
		this.on_jsdialog = on_jsdialog;
		this.on_before_unload_dialog = on_before_unload_dialog;
		this.on_reset_dialog_state = on_reset_dialog_state;
		this.on_dialog_closed = on_dialog_closed;
	}
	public cef_jsdialog_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_jsdialog_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_jsdialog_handler_t implements Structure.ByValue {
		
	};
}
