package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_menu_model_capi.h:105</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_menu_model_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : clear_callback* */
	public cef_menu_model_t.clear_callback clear;
	/** C type : get_count_callback* */
	public cef_menu_model_t.get_count_callback get_count;
	/** C type : add_separator_callback* */
	public cef_menu_model_t.add_separator_callback add_separator;
	/** C type : add_item_callback* */
	public cef_menu_model_t.add_item_callback add_item;
	/** C type : add_check_item_callback* */
	public cef_menu_model_t.add_check_item_callback add_check_item;
	/** C type : add_radio_item_callback* */
	public cef_menu_model_t.add_radio_item_callback add_radio_item;
	/** C type : add_sub_menu_callback* */
	public cef_menu_model_t.add_sub_menu_callback add_sub_menu;
	/** C type : insert_separator_at_callback* */
	public cef_menu_model_t.insert_separator_at_callback insert_separator_at;
	/** C type : insert_item_at_callback* */
	public cef_menu_model_t.insert_item_at_callback insert_item_at;
	/** C type : insert_check_item_at_callback* */
	public cef_menu_model_t.insert_check_item_at_callback insert_check_item_at;
	/** C type : insert_radio_item_at_callback* */
	public cef_menu_model_t.insert_radio_item_at_callback insert_radio_item_at;
	/** C type : insert_sub_menu_at_callback* */
	public cef_menu_model_t.insert_sub_menu_at_callback insert_sub_menu_at;
	/** C type : remove_callback* */
	public cef_menu_model_t.remove_callback remove;
	/** C type : remove_at_callback* */
	public cef_menu_model_t.remove_at_callback remove_at;
	/** C type : get_index_of_callback* */
	public cef_menu_model_t.get_index_of_callback get_index_of;
	/** C type : get_command_id_at_callback* */
	public cef_menu_model_t.get_command_id_at_callback get_command_id_at;
	/** C type : set_command_id_at_callback* */
	public cef_menu_model_t.set_command_id_at_callback set_command_id_at;
	/** C type : set_label_callback* */
	public cef_menu_model_t.set_label_callback set_label;
	/** C type : set_label_at_callback* */
	public cef_menu_model_t.set_label_at_callback set_label_at;
	/** C type : get_group_id_callback* */
	public cef_menu_model_t.get_group_id_callback get_group_id;
	/** C type : get_group_id_at_callback* */
	public cef_menu_model_t.get_group_id_at_callback get_group_id_at;
	/** C type : set_group_id_callback* */
	public cef_menu_model_t.set_group_id_callback set_group_id;
	/** C type : set_group_id_at_callback* */
	public cef_menu_model_t.set_group_id_at_callback set_group_id_at;
	/** C type : get_sub_menu_callback* */
	public cef_menu_model_t.get_sub_menu_callback get_sub_menu;
	/** C type : get_sub_menu_at_callback* */
	public cef_menu_model_t.get_sub_menu_at_callback get_sub_menu_at;
	/** C type : is_visible_callback* */
	public cef_menu_model_t.is_visible_callback is_visible;
	/** C type : is_visible_at_callback* */
	public cef_menu_model_t.is_visible_at_callback is_visible_at;
	/** C type : set_visible_callback* */
	public cef_menu_model_t.set_visible_callback set_visible;
	/** C type : set_visible_at_callback* */
	public cef_menu_model_t.set_visible_at_callback set_visible_at;
	/** C type : is_enabled_callback* */
	public cef_menu_model_t.is_enabled_callback is_enabled;
	/** C type : is_enabled_at_callback* */
	public cef_menu_model_t.is_enabled_at_callback is_enabled_at;
	/** C type : set_enabled_callback* */
	public cef_menu_model_t.set_enabled_callback set_enabled;
	/** C type : set_enabled_at_callback* */
	public cef_menu_model_t.set_enabled_at_callback set_enabled_at;
	/** C type : is_checked_callback* */
	public cef_menu_model_t.is_checked_callback is_checked;
	/** C type : is_checked_at_callback* */
	public cef_menu_model_t.is_checked_at_callback is_checked_at;
	/** C type : set_checked_callback* */
	public cef_menu_model_t.set_checked_callback set_checked;
	/** C type : set_checked_at_callback* */
	public cef_menu_model_t.set_checked_at_callback set_checked_at;
	/** C type : has_accelerator_callback* */
	public cef_menu_model_t.has_accelerator_callback has_accelerator;
	/** C type : has_accelerator_at_callback* */
	public cef_menu_model_t.has_accelerator_at_callback has_accelerator_at;
	/** C type : set_accelerator_callback* */
	public cef_menu_model_t.set_accelerator_callback set_accelerator;
	/** C type : set_accelerator_at_callback* */
	public cef_menu_model_t.set_accelerator_at_callback set_accelerator_at;
	/** C type : remove_accelerator_callback* */
	public cef_menu_model_t.remove_accelerator_callback remove_accelerator;
	/** C type : remove_accelerator_at_callback* */
	public cef_menu_model_t.remove_accelerator_at_callback remove_accelerator_at;
	/** C type : get_accelerator_callback* */
	public cef_menu_model_t.get_accelerator_callback get_accelerator;
	/** C type : get_accelerator_at_callback* */
	public cef_menu_model_t.get_accelerator_at_callback get_accelerator_at;
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:56</i> */
	public interface clear_callback extends Callback {
		int apply(cef_menu_model_t self);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:57</i> */
	public interface get_count_callback extends Callback {
		int apply(cef_menu_model_t self);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:58</i> */
	public interface add_separator_callback extends Callback {
		int apply(cef_menu_model_t self);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:59</i> */
	public interface add_item_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:60</i> */
	public interface add_check_item_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:61</i> */
	public interface add_radio_item_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, cef_string_utf16_t label, int group_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:62</i> */
	public interface add_sub_menu_callback extends Callback {
		cef_menu_model_t apply(cef_menu_model_t self, int command_id, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:63</i> */
	public interface insert_separator_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:64</i> */
	public interface insert_item_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int command_id, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:65</i> */
	public interface insert_check_item_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int command_id, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:66</i> */
	public interface insert_radio_item_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int command_id, cef_string_utf16_t label, int group_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:67</i> */
	public interface insert_sub_menu_at_callback extends Callback {
		cef_menu_model_t apply(cef_menu_model_t self, int index, int command_id, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:68</i> */
	public interface remove_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:69</i> */
	public interface remove_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:70</i> */
	public interface get_index_of_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:71</i> */
	public interface get_command_id_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:72</i> */
	public interface set_command_id_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:73</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:74</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:75</i> */
	public interface set_label_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:76</i> */
	public interface set_label_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, cef_string_utf16_t label);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:77</i> */
	public interface cef_menu_item_type_t_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:78</i> */
	public interface cef_menu_item_type_t_callback2 extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:79</i> */
	public interface get_group_id_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:80</i> */
	public interface get_group_id_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:81</i> */
	public interface set_group_id_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, int group_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:82</i> */
	public interface set_group_id_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int group_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:83</i> */
	public interface get_sub_menu_callback extends Callback {
		cef_menu_model_t apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:84</i> */
	public interface get_sub_menu_at_callback extends Callback {
		cef_menu_model_t apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:85</i> */
	public interface is_visible_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:86</i> */
	public interface is_visible_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:87</i> */
	public interface set_visible_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, int visible);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:88</i> */
	public interface set_visible_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int visible);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:89</i> */
	public interface is_enabled_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:90</i> */
	public interface is_enabled_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:91</i> */
	public interface set_enabled_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, int enabled);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:92</i> */
	public interface set_enabled_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int enabled);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:93</i> */
	public interface is_checked_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:94</i> */
	public interface is_checked_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:95</i> */
	public interface set_checked_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, int checked);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:96</i> */
	public interface set_checked_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int checked);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:97</i> */
	public interface has_accelerator_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:98</i> */
	public interface has_accelerator_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:99</i> */
	public interface set_accelerator_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, int key_code, int shift_pressed, int ctrl_pressed, int alt_pressed);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:100</i> */
	public interface set_accelerator_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, int key_code, int shift_pressed, int ctrl_pressed, int alt_pressed);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:101</i> */
	public interface remove_accelerator_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:102</i> */
	public interface remove_accelerator_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:103</i> */
	public interface get_accelerator_callback extends Callback {
		int apply(cef_menu_model_t self, int command_id, IntByReference key_code, IntByReference shift_pressed, IntByReference ctrl_pressed, IntByReference alt_pressed);
	};
	/** <i>native declaration : include\capi\cef_menu_model_capi.h:104</i> */
	public interface get_accelerator_at_callback extends Callback {
		int apply(cef_menu_model_t self, int index, IntByReference key_code, IntByReference shift_pressed, IntByReference ctrl_pressed, IntByReference alt_pressed);
	};
	public cef_menu_model_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "clear", "get_count", "add_separator", "add_item", "add_check_item", "add_radio_item", "add_sub_menu", "insert_separator_at", "insert_item_at", "insert_check_item_at", "insert_radio_item_at", "insert_sub_menu_at", "remove", "remove_at", "get_index_of", "get_command_id_at", "set_command_id_at", "set_label", "set_label_at", "get_group_id", "get_group_id_at", "set_group_id", "set_group_id_at", "get_sub_menu", "get_sub_menu_at", "is_visible", "is_visible_at", "set_visible", "set_visible_at", "is_enabled", "is_enabled_at", "set_enabled", "set_enabled_at", "is_checked", "is_checked_at", "set_checked", "set_checked_at", "has_accelerator", "has_accelerator_at", "set_accelerator", "set_accelerator_at", "remove_accelerator", "remove_accelerator_at", "get_accelerator", "get_accelerator_at");
	}
	public cef_menu_model_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_menu_model_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_menu_model_t implements Structure.ByValue {
		
	};
}
