package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_resource_handler_capi.h:15</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_resource_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : process_request_callback* */
	public cef_resource_handler_t.process_request_callback process_request;
	/** C type : get_response_headers_callback* */
	public cef_resource_handler_t.get_response_headers_callback get_response_headers;
	/** C type : read_response_callback* */
	public cef_resource_handler_t.read_response_callback read_response;
	/** C type : can_get_cookie_callback* */
	public cef_resource_handler_t.can_get_cookie_callback can_get_cookie;
	/** C type : can_set_cookie_callback* */
	public cef_resource_handler_t.can_set_cookie_callback can_set_cookie;
	/** C type : cancel_callback* */
	public cef.cef_urlrequest_t.cancel_callback cancel;
	/** <i>native declaration : include\capi\cef_resource_handler_capi.h:9</i> */
	public interface process_request_callback extends Callback {
		int apply(cef_resource_handler_t self, cef_request_t request, cef_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_resource_handler_capi.h:10</i> */
	public interface get_response_headers_callback extends Callback {
		void apply(cef_resource_handler_t self, cef_response_t response, LongByReference response_length, cef_string_utf16_t redirectUrl);
	};
	/** <i>native declaration : include\capi\cef_resource_handler_capi.h:11</i> */
	public interface read_response_callback extends Callback {
		int apply(cef_resource_handler_t self, Pointer data_out, int bytes_to_read, IntByReference bytes_read, cef_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_resource_handler_capi.h:12</i> */
	public interface can_get_cookie_callback extends Callback {
		int apply(cef_resource_handler_t self, cef_cookie_t cookie);
	};
	/** <i>native declaration : include\capi\cef_resource_handler_capi.h:13</i> */
	public interface can_set_cookie_callback extends Callback {
		int apply(cef_resource_handler_t self, cef_cookie_t cookie);
	};
	/** <i>native declaration : include\capi\cef_resource_handler_capi.h:14</i> */
	public interface cancel_callback extends Callback {
		void apply(cef_resource_handler_t self);
	};
	public cef_resource_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "process_request", "get_response_headers", "read_response", "can_get_cookie", "can_set_cookie", "cancel");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param process_request C type : process_request_callback*<br>
	 * @param get_response_headers C type : get_response_headers_callback*<br>
	 * @param read_response C type : read_response_callback*<br>
	 * @param can_get_cookie C type : can_get_cookie_callback*<br>
	 * @param can_set_cookie C type : can_set_cookie_callback*<br>
	 * @param cancel C type : cancel_callback*
	 */
	public cef_resource_handler_t(cef_base_t base, cef_resource_handler_t.process_request_callback process_request, cef_resource_handler_t.get_response_headers_callback get_response_headers, cef_resource_handler_t.read_response_callback read_response, cef_resource_handler_t.can_get_cookie_callback can_get_cookie, cef_resource_handler_t.can_set_cookie_callback can_set_cookie, cef.cef_urlrequest_t.cancel_callback cancel) {
		super();
		this.base = base;
		this.process_request = process_request;
		this.get_response_headers = get_response_headers;
		this.read_response = read_response;
		this.can_get_cookie = can_get_cookie;
		this.can_set_cookie = can_set_cookie;
		this.cancel = cancel;
	}
	public cef_resource_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_resource_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_resource_handler_t implements Structure.ByValue {
		
	};
}
