package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:87</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_browser_settings_t extends Structure {
	public int size;
	public int windowless_frame_rate;
	/** C type : cef_string_t */
	public cef_string_utf16_t standard_font_family;
	/** C type : cef_string_t */
	public cef_string_utf16_t fixed_font_family;
	/** C type : cef_string_t */
	public cef_string_utf16_t serif_font_family;
	/** C type : cef_string_t */
	public cef_string_utf16_t sans_serif_font_family;
	/** C type : cef_string_t */
	public cef_string_utf16_t cursive_font_family;
	/** C type : cef_string_t */
	public cef_string_utf16_t fantasy_font_family;
	public int default_font_size;
	public int default_fixed_font_size;
	public int minimum_font_size;
	public int minimum_logical_font_size;
	/** C type : cef_string_t */
	public cef_string_utf16_t default_encoding;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int remote_fonts;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int javascript;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int javascript_open_windows;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int javascript_close_windows;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int javascript_access_clipboard;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int javascript_dom_paste;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int caret_browsing;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int plugins;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int universal_access_from_file_urls;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int file_access_from_file_urls;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int web_security;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int image_loading;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int image_shrink_standalone_to_fit;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int text_area_resize;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int tab_to_links;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int local_storage;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int databases;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int application_cache;
	/**
	 * @see cef_state_t<br>
	 * C type : cef_state_t
	 */
	public int webgl;
	/** C type : cef_color_t */
	public int background_color;
	/** C type : cef_string_t */
	public cef_string_utf16_t accept_language_list;
	public cef_browser_settings_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("size", "windowless_frame_rate", "standard_font_family", "fixed_font_family", "serif_font_family", "sans_serif_font_family", "cursive_font_family", "fantasy_font_family", "default_font_size", "default_fixed_font_size", "minimum_font_size", "minimum_logical_font_size", "default_encoding", "remote_fonts", "javascript", "javascript_open_windows", "javascript_close_windows", "javascript_access_clipboard", "javascript_dom_paste", "caret_browsing", "plugins", "universal_access_from_file_urls", "file_access_from_file_urls", "web_security", "image_loading", "image_shrink_standalone_to_fit", "text_area_resize", "tab_to_links", "local_storage", "databases", "application_cache", "webgl", "background_color", "accept_language_list");
	}
	public cef_browser_settings_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_browser_settings_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_browser_settings_t implements Structure.ByValue {
		
	};
}
