package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_urlrequest_capi.h:18</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_urlrequest_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_request_callback* */
	public cef_urlrequest_t.get_request_callback get_request;
	/** C type : get_client_callback* */
	public cef_urlrequest_t.get_client_callback get_client;
	/** C type : get_response_callback* */
	public cef_urlrequest_t.get_response_callback get_response;
	/** C type : cancel_callback* */
	public cef_urlrequest_t.cancel_callback cancel;
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:12</i> */
	public interface get_request_callback extends Callback {
		cef_request_t apply(cef_urlrequest_t self);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:13</i> */
	public interface get_client_callback extends Callback {
		cef_urlrequest_client_t apply(cef_urlrequest_t self);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:14</i> */
	public interface cef_urlrequest_status_t_callback extends Callback {
		int apply(cef_urlrequest_t self);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:15</i> */
	public interface cef_errorcode_t_callback extends Callback {
		int apply(cef_urlrequest_t self);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:16</i> */
	public interface get_response_callback extends Callback {
		cef_response_t apply(cef_urlrequest_t self);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:17</i> */
	public interface cancel_callback extends Callback {
		void apply(cef_urlrequest_t self);
	};
	public cef_urlrequest_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_request", "get_client", "get_response", "cancel");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param get_request C type : get_request_callback*<br>
	 * @param get_client C type : get_client_callback*<br>
	 * @param get_response C type : get_response_callback*<br>
	 * @param cancel C type : cancel_callback*
	 */
	public cef_urlrequest_t(cef_base_t base, cef_urlrequest_t.get_request_callback get_request, cef_urlrequest_t.get_client_callback get_client, cef_urlrequest_t.get_response_callback get_response, cef_urlrequest_t.cancel_callback cancel) {
		super();
		this.base = base;
		this.get_request = get_request;
		this.get_client = get_client;
		this.get_response = get_response;
		this.cancel = cancel;
	}
	public cef_urlrequest_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_urlrequest_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_urlrequest_t implements Structure.ByValue {
		
	};
}
