package cef;
import cef.CefLibrary._cef_frame_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_context_menu_handler_capi.h:19</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_context_menu_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_before_context_menu_callback* */
	public cef_context_menu_handler_t.on_before_context_menu_callback on_before_context_menu;
	/** C type : run_context_menu_callback* */
	public cef_context_menu_handler_t.run_context_menu_callback run_context_menu;
	/** C type : on_context_menu_command_callback* */
	public cef_context_menu_handler_t.on_context_menu_command_callback on_context_menu_command;
	/** C type : on_context_menu_dismissed_callback* */
	public cef_context_menu_handler_t.on_context_menu_dismissed_callback on_context_menu_dismissed;
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:15</i> */
	public interface on_before_context_menu_callback extends Callback {
		void apply(cef_context_menu_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_context_menu_params_t params, cef_menu_model_t model);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:16</i> */
	public interface run_context_menu_callback extends Callback {
		int apply(cef_context_menu_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_context_menu_params_t params, cef_menu_model_t model, cef_run_context_menu_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:17</i> */
	public interface on_context_menu_command_callback extends Callback {
		int apply(cef_context_menu_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_context_menu_params_t params, int command_id, int event_flags);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:18</i> */
	public interface on_context_menu_dismissed_callback extends Callback {
		void apply(cef_context_menu_handler_t self, cef_browser_t browser, _cef_frame_t frame);
	};
	public cef_context_menu_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_before_context_menu", "run_context_menu", "on_context_menu_command", "on_context_menu_dismissed");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_before_context_menu C type : on_before_context_menu_callback*<br>
	 * @param run_context_menu C type : run_context_menu_callback*<br>
	 * @param on_context_menu_command C type : on_context_menu_command_callback*<br>
	 * @param on_context_menu_dismissed C type : on_context_menu_dismissed_callback*
	 */
	public cef_context_menu_handler_t(cef_base_t base, cef_context_menu_handler_t.on_before_context_menu_callback on_before_context_menu, cef_context_menu_handler_t.run_context_menu_callback run_context_menu, cef_context_menu_handler_t.on_context_menu_command_callback on_context_menu_command, cef_context_menu_handler_t.on_context_menu_dismissed_callback on_context_menu_dismissed) {
		super();
		this.base = base;
		this.on_before_context_menu = on_before_context_menu;
		this.run_context_menu = run_context_menu;
		this.on_context_menu_command = on_context_menu_command;
		this.on_context_menu_dismissed = on_context_menu_dismissed;
	}
	public cef_context_menu_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_context_menu_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_context_menu_handler_t implements Structure.ByValue {
		
	};
}
