package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:115</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_cookie_t extends Structure {
	/** C type : cef_string_t */
	public cef_string_utf16_t name;
	/** C type : cef_string_t */
	public cef_string_utf16_t value;
	/** C type : cef_string_t */
	public cef_string_utf16_t domain;
	/** C type : cef_string_t */
	public cef_string_utf16_t path;
	public int secure;
	public int httponly;
	/** C type : cef_time_t */
	public cef_time_t creation;
	/** C type : cef_time_t */
	public cef_time_t last_access;
	public int has_expires;
	/** C type : cef_time_t */
	public cef_time_t expires;
	public cef_cookie_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("name", "value", "domain", "path", "secure", "httponly", "creation", "last_access", "has_expires", "expires");
	}
	public cef_cookie_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_cookie_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_cookie_t implements Structure.ByValue {
		
	};
}
