package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_web_plugin_capi.h:26</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_web_plugin_unstable_callback_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : is_unstable_callback* */
	public cef_web_plugin_unstable_callback_t.is_unstable_callback is_unstable;
	/** <i>native declaration : include\capi\cef_web_plugin_capi.h:25</i> */
	public interface is_unstable_callback extends Callback {
		void apply(cef_web_plugin_unstable_callback_t self, cef_string_utf16_t path, int unstable);
	};
	public cef_web_plugin_unstable_callback_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "is_unstable");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param is_unstable C type : is_unstable_callback*
	 */
	public cef_web_plugin_unstable_callback_t(cef_base_t base, cef_web_plugin_unstable_callback_t.is_unstable_callback is_unstable) {
		super();
		this.base = base;
		this.is_unstable = is_unstable;
	}
	public cef_web_plugin_unstable_callback_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_web_plugin_unstable_callback_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_web_plugin_unstable_callback_t implements Structure.ByValue {
		
	};
}
