package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_download_handler_capi.h:21</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_download_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_before_download_callback* */
	public cef_download_handler_t.on_before_download_callback on_before_download;
	/** C type : on_download_updated_callback* */
	public cef_download_handler_t.on_download_updated_callback on_download_updated;
	/** <i>native declaration : include\capi\cef_download_handler_capi.h:19</i> */
	public interface on_before_download_callback extends Callback {
		void apply(cef_download_handler_t self, cef_browser_t browser, cef_download_item_t download_item, cef_string_utf16_t suggested_name, cef_before_download_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_download_handler_capi.h:20</i> */
	public interface on_download_updated_callback extends Callback {
		void apply(cef_download_handler_t self, cef_browser_t browser, cef_download_item_t download_item, cef_download_item_callback_t callback);
	};
	public cef_download_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_before_download", "on_download_updated");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_before_download C type : on_before_download_callback*<br>
	 * @param on_download_updated C type : on_download_updated_callback*
	 */
	public cef_download_handler_t(cef_base_t base, cef_download_handler_t.on_before_download_callback on_before_download, cef_download_handler_t.on_download_updated_callback on_download_updated) {
		super();
		this.base = base;
		this.on_before_download = on_before_download;
		this.on_download_updated = on_download_updated;
	}
	public cef_download_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_download_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_download_handler_t implements Structure.ByValue {
		
	};
}
