package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_time.h:17</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_time_t extends Structure {
	/** Four digit year "2007" */
	public int year;
	/** 1-based month (values 1 = January, etc.) */
	public int month;
	/** 0-based day of week (0 = Sunday, etc.) */
	public int day_of_week;
	/** 1-based day of month (1-31) */
	public int day_of_month;
	/** Hour within the current day (0-23) */
	public int hour;
	/** Minute within the current hour (0-59) */
	public int minute;
	/** Second within the current minute (0-59 plus leap */
	public int second;
	/** Milliseconds within the current second (0-999) */
	public int millisecond;
	public cef_time_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("year", "month", "day_of_week", "day_of_month", "hour", "minute", "second", "millisecond");
	}
	/**
	 * @param year Four digit year "2007"<br>
	 * @param month 1-based month (values 1 = January, etc.)<br>
	 * @param day_of_week 0-based day of week (0 = Sunday, etc.)<br>
	 * @param day_of_month 1-based day of month (1-31)<br>
	 * @param hour Hour within the current day (0-23)<br>
	 * @param minute Minute within the current hour (0-59)<br>
	 * @param second Second within the current minute (0-59 plus leap<br>
	 * @param millisecond Milliseconds within the current second (0-999)
	 */
	public cef_time_t(int year, int month, int day_of_week, int day_of_month, int hour, int minute, int second, int millisecond) {
		super();
		this.year = year;
		this.month = month;
		this.day_of_week = day_of_week;
		this.day_of_month = day_of_month;
		this.hour = hour;
		this.minute = minute;
		this.second = second;
		this.millisecond = millisecond;
	}
	public cef_time_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_time_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_time_t implements Structure.ByValue {
		
	};
}
