package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_menu_model_delegate_capi.h:8</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_menu_model_delegate_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : execute_command_callback* */
	public cef_menu_model_delegate_t.execute_command_callback execute_command;
	/** C type : menu_will_show_callback* */
	public cef_menu_model_delegate_t.menu_will_show_callback menu_will_show;
	/** <i>native declaration : include\capi\cef_menu_model_delegate_capi.h:6</i> */
	public interface execute_command_callback extends Callback {
		void apply(cef_menu_model_delegate_t self, cef_menu_model_t menu_model, int command_id, int event_flags);
	};
	/** <i>native declaration : include\capi\cef_menu_model_delegate_capi.h:7</i> */
	public interface menu_will_show_callback extends Callback {
		void apply(cef_menu_model_delegate_t self, cef_menu_model_t menu_model);
	};
	public cef_menu_model_delegate_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "execute_command", "menu_will_show");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param execute_command C type : execute_command_callback*<br>
	 * @param menu_will_show C type : menu_will_show_callback*
	 */
	public cef_menu_model_delegate_t(cef_base_t base, cef_menu_model_delegate_t.execute_command_callback execute_command, cef_menu_model_delegate_t.menu_will_show_callback menu_will_show) {
		super();
		this.base = base;
		this.execute_command = execute_command;
		this.menu_will_show = menu_will_show;
	}
	public cef_menu_model_delegate_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_menu_model_delegate_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_menu_model_delegate_t implements Structure.ByValue {
		
	};
}
