package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_focus_handler_capi.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_focus_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_take_focus_callback* */
	public cef_focus_handler_t.on_take_focus_callback on_take_focus;
	/** C type : on_set_focus_callback* */
	public cef_focus_handler_t.on_set_focus_callback on_set_focus;
	/** C type : on_got_focus_callback* */
	public cef_focus_handler_t.on_got_focus_callback on_got_focus;
	/** <i>native declaration : include\capi\cef_focus_handler_capi.h:6</i> */
	public interface on_take_focus_callback extends Callback {
		void apply(cef_focus_handler_t self, cef_browser_t browser, int next);
	};
	/** <i>native declaration : include\capi\cef_focus_handler_capi.h:7</i> */
	public interface on_set_focus_callback extends Callback {
		int apply(cef_focus_handler_t self, cef_browser_t browser, int source);
	};
	/** <i>native declaration : include\capi\cef_focus_handler_capi.h:8</i> */
	public interface on_got_focus_callback extends Callback {
		void apply(cef_focus_handler_t self, cef_browser_t browser);
	};
	public cef_focus_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_take_focus", "on_set_focus", "on_got_focus");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_take_focus C type : on_take_focus_callback*<br>
	 * @param on_set_focus C type : on_set_focus_callback*<br>
	 * @param on_got_focus C type : on_got_focus_callback*
	 */
	public cef_focus_handler_t(cef_base_t base, cef_focus_handler_t.on_take_focus_callback on_take_focus, cef_focus_handler_t.on_set_focus_callback on_set_focus, cef_focus_handler_t.on_got_focus_callback on_got_focus) {
		super();
		this.base = base;
		this.on_take_focus = on_take_focus;
		this.on_set_focus = on_set_focus;
		this.on_got_focus = on_got_focus;
	}
	public cef_focus_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_focus_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_focus_handler_t implements Structure.ByValue {
		
	};
}
