package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_v8_capi.h:36</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_v8handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : execute_callback* */
	public cef_v8handler_t.execute_callback execute;
	/** <i>native declaration : include\capi\cef_v8_capi.h:35</i> */
	public interface execute_callback extends Callback {
		int apply(cef_v8handler_t self, cef_string_utf16_t name, cef_v8value_t object, int argumentsCount, PointerByReference arguments, PointerByReference retval, cef_string_utf16_t exception);
	};
	public cef_v8handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "execute");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param execute C type : execute_callback*
	 */
	public cef_v8handler_t(cef_base_t base, cef_v8handler_t.execute_callback execute) {
		super();
		this.base = base;
		this.execute = execute;
	}
	public cef_v8handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_v8handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_v8handler_t implements Structure.ByValue {
		
	};
}
