package cef;
import cef.CefLibrary._cef_binary_value_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_ssl_info_capi.h:58</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_sslinfo_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : is_cert_status_error_callback* */
	public cef_sslinfo_t.is_cert_status_error_callback is_cert_status_error;
	/** C type : is_cert_status_minor_error_callback* */
	public cef_sslinfo_t.is_cert_status_minor_error_callback is_cert_status_minor_error;
	/** C type : get_subject_callback* */
	public cef_sslinfo_t.get_subject_callback get_subject;
	/** C type : get_issuer_callback* */
	public cef_sslinfo_t.get_issuer_callback get_issuer;
	/** C type : get_serial_number_callback* */
	public cef_sslinfo_t.get_serial_number_callback get_serial_number;
	/** C type : get_derencoded_callback* */
	public cef_sslinfo_t.get_derencoded_callback get_derencoded;
	/** C type : get_pemencoded_callback* */
	public cef_sslinfo_t.get_pemencoded_callback get_pemencoded;
	/** C type : get_issuer_chain_size_callback* */
	public cef_sslinfo_t.get_issuer_chain_size_callback get_issuer_chain_size;
	/** C type : get_derencoded_issuer_chain_callback* */
	public cef_sslinfo_t.get_derencoded_issuer_chain_callback get_derencoded_issuer_chain;
	/** C type : get_pemencoded_issuer_chain_callback* */
	public cef_sslinfo_t.get_pemencoded_issuer_chain_callback get_pemencoded_issuer_chain;
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:45</i> */
	public interface cef_cert_status_t_callback extends Callback {
		int apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:46</i> */
	public interface is_cert_status_error_callback extends Callback {
		int apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:47</i> */
	public interface is_cert_status_minor_error_callback extends Callback {
		int apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:48</i> */
	public interface get_subject_callback extends Callback {
		cef_sslcert_principal_t apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:49</i> */
	public interface get_issuer_callback extends Callback {
		cef_sslcert_principal_t apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:50</i> */
	public interface get_serial_number_callback extends Callback {
		_cef_binary_value_t apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:51</i> */
	public interface cef_time_t_callback extends Callback {
		int apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:52</i> */
	public interface cef_time_t_callback2 extends Callback {
		int apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:53</i> */
	public interface get_derencoded_callback extends Callback {
		_cef_binary_value_t apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:54</i> */
	public interface get_pemencoded_callback extends Callback {
		_cef_binary_value_t apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:55</i> */
	public interface get_issuer_chain_size_callback extends Callback {
		int apply(cef_sslinfo_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:56</i> */
	public interface get_derencoded_issuer_chain_callback extends Callback {
		void apply(cef_sslinfo_t self, IntByReference chainCount, PointerByReference chain);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:57</i> */
	public interface get_pemencoded_issuer_chain_callback extends Callback {
		void apply(cef_sslinfo_t self, IntByReference chainCount, PointerByReference chain);
	};
	public cef_sslinfo_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "is_cert_status_error", "is_cert_status_minor_error", "get_subject", "get_issuer", "get_serial_number", "get_derencoded", "get_pemencoded", "get_issuer_chain_size", "get_derencoded_issuer_chain", "get_pemencoded_issuer_chain");
	}
	public cef_sslinfo_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_sslinfo_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_sslinfo_t implements Structure.ByValue {
		
	};
}
