package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_request_context_capi.h:6</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_resolve_callback_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_resolve_completed_callback* */
	public cef_resolve_callback_t.on_resolve_completed_callback on_resolve_completed;
	/** <i>native declaration : include\capi\cef_request_context_capi.h:5</i> */
	public interface on_resolve_completed_callback extends Callback {
		void apply(cef_resolve_callback_t self, int result, Pointer resolved_ips);
	};
	public cef_resolve_callback_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_resolve_completed");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_resolve_completed C type : on_resolve_completed_callback*
	 */
	public cef_resolve_callback_t(cef_base_t base, cef_resolve_callback_t.on_resolve_completed_callback on_resolve_completed) {
		super();
		this.base = base;
		this.on_resolve_completed = on_resolve_completed;
	}
	public cef_resolve_callback_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_resolve_callback_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_resolve_callback_t implements Structure.ByValue {
		
	};
}
