package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_stream_capi.h:13</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_read_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : read_callback* */
	public cef.cef_stream_reader_t.read_callback read;
	/** C type : seek_callback* */
	public cef.cef_stream_writer_t.seek_callback seek;
	/** C type : tell_callback* */
	public cef.cef_stream_writer_t.tell_callback tell;
	/** C type : eof_callback* */
	public cef.cef_zip_reader_t.eof_callback eof;
	/** C type : may_block_callback* */
	public cef.cef_stream_writer_t.may_block_callback may_block;
	/** <i>native declaration : include\capi\cef_stream_capi.h:8</i> */
	public interface read_callback extends Callback {
		int apply(cef_read_handler_t self, Pointer ptr, int size, int n);
	};
	/** <i>native declaration : include\capi\cef_stream_capi.h:9</i> */
	public interface seek_callback extends Callback {
		int apply(cef_read_handler_t self, long offset, int whence);
	};
	/** <i>native declaration : include\capi\cef_stream_capi.h:10</i> */
	public interface tell_callback extends Callback {
		long apply(cef_read_handler_t self);
	};
	/** <i>native declaration : include\capi\cef_stream_capi.h:11</i> */
	public interface eof_callback extends Callback {
		int apply(cef_read_handler_t self);
	};
	/** <i>native declaration : include\capi\cef_stream_capi.h:12</i> */
	public interface may_block_callback extends Callback {
		int apply(cef_read_handler_t self);
	};
	public cef_read_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "read", "seek", "tell", "eof", "may_block");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param read C type : read_callback*<br>
	 * @param seek C type : seek_callback*<br>
	 * @param tell C type : tell_callback*<br>
	 * @param eof C type : eof_callback*<br>
	 * @param may_block C type : may_block_callback*
	 */
	public cef_read_handler_t(cef_base_t base, cef.cef_stream_reader_t.read_callback read, cef.cef_stream_writer_t.seek_callback seek, cef.cef_stream_writer_t.tell_callback tell, cef.cef_zip_reader_t.eof_callback eof, cef.cef_stream_writer_t.may_block_callback may_block) {
		super();
		this.base = base;
		this.read = read;
		this.seek = seek;
		this.tell = tell;
		this.eof = eof;
		this.may_block = may_block;
	}
	public cef_read_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_read_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_read_handler_t implements Structure.ByValue {
		
	};
}
