package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_dom_capi.h:105</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_domnode_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : is_text_callback* */
	public cef_domnode_t.is_text_callback is_text;
	/** C type : is_element_callback* */
	public cef_domnode_t.is_element_callback is_element;
	/** C type : is_editable_callback* */
	public cef.cef_context_menu_params_t.is_editable_callback is_editable;
	/** C type : is_form_control_element_callback* */
	public cef_domnode_t.is_form_control_element_callback is_form_control_element;
	/** C type : is_same_callback* */
	public cef.cef_v8value_t.is_same_callback is_same;
	/** C type : set_value_callback* */
	public cef_domnode_t.set_value_callback set_value;
	/** C type : get_document_callback* */
	public cef_domnode_t.get_document_callback get_document;
	/** C type : get_parent_callback* */
	public cef_domnode_t.get_parent_callback get_parent;
	/** C type : get_previous_sibling_callback* */
	public cef_domnode_t.get_previous_sibling_callback get_previous_sibling;
	/** C type : get_next_sibling_callback* */
	public cef_domnode_t.get_next_sibling_callback get_next_sibling;
	/** C type : has_children_callback* */
	public cef_domnode_t.has_children_callback has_children;
	/** C type : get_first_child_callback* */
	public cef_domnode_t.get_first_child_callback get_first_child;
	/** C type : get_last_child_callback* */
	public cef_domnode_t.get_last_child_callback get_last_child;
	/** C type : has_element_attributes_callback* */
	public cef_domnode_t.has_element_attributes_callback has_element_attributes;
	/** C type : has_element_attribute_callback* */
	public cef_domnode_t.has_element_attribute_callback has_element_attribute;
	/** C type : get_element_attributes_callback* */
	public cef_domnode_t.get_element_attributes_callback get_element_attributes;
	/** C type : set_element_attribute_callback* */
	public cef_domnode_t.set_element_attribute_callback set_element_attribute;
	/** <i>native declaration : include\capi\cef_dom_capi.h:80</i> */
	public interface cef_dom_node_type_t_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:81</i> */
	public interface is_text_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:82</i> */
	public interface is_element_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:83</i> */
	public interface is_editable_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:84</i> */
	public interface is_form_control_element_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:85</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:86</i> */
	public interface is_same_callback extends Callback {
		int apply(cef_domnode_t self, cef_domnode_t that);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:87</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:88</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:89</i> */
	public interface set_value_callback extends Callback {
		int apply(cef_domnode_t self, cef_string_utf16_t value);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:90</i> */
	public interface cef_string_userfree_t_callback4 extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:91</i> */
	public interface get_document_callback extends Callback {
		cef_domdocument_t apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:92</i> */
	public interface get_parent_callback extends Callback {
		cef_domnode_t apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:93</i> */
	public interface get_previous_sibling_callback extends Callback {
		cef_domnode_t apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:94</i> */
	public interface get_next_sibling_callback extends Callback {
		cef_domnode_t apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:95</i> */
	public interface has_children_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:96</i> */
	public interface get_first_child_callback extends Callback {
		cef_domnode_t apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:97</i> */
	public interface get_last_child_callback extends Callback {
		cef_domnode_t apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:98</i> */
	public interface cef_string_userfree_t_callback5 extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:99</i> */
	public interface has_element_attributes_callback extends Callback {
		int apply(cef_domnode_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:100</i> */
	public interface has_element_attribute_callback extends Callback {
		int apply(cef_domnode_t self, cef_string_utf16_t attrName);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:101</i> */
	public interface cef_string_userfree_t_callback6 extends Callback {
		int apply(cef_domnode_t self, cef_string_utf16_t attrName);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:102</i> */
	public interface get_element_attributes_callback extends Callback {
		void apply(cef_domnode_t self, Pointer attrMap);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:103</i> */
	public interface set_element_attribute_callback extends Callback {
		int apply(cef_domnode_t self, cef_string_utf16_t attrName, cef_string_utf16_t value);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:104</i> */
	public interface cef_string_userfree_t_callback7 extends Callback {
		int apply(cef_domnode_t self);
	};
	public cef_domnode_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "is_text", "is_element", "is_editable", "is_form_control_element", "is_same", "set_value", "get_document", "get_parent", "get_previous_sibling", "get_next_sibling", "has_children", "get_first_child", "get_last_child", "has_element_attributes", "has_element_attribute", "get_element_attributes", "set_element_attribute");
	}
	public cef_domnode_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_domnode_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_domnode_t implements Structure.ByValue {
		
	};
}
