package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:547</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_popup_features_t extends Structure {
	public int x;
	public int xSet;
	public int y;
	public int ySet;
	public int width;
	public int widthSet;
	public int height;
	public int heightSet;
	public int menuBarVisible;
	public int statusBarVisible;
	public int toolBarVisible;
	public int locationBarVisible;
	public int scrollbarsVisible;
	public int resizable;
	public int fullscreen;
	public int dialog;
	/** C type : cef_string_list_t */
	public Pointer additionalFeatures;
	public cef_popup_features_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("x", "xSet", "y", "ySet", "width", "widthSet", "height", "heightSet", "menuBarVisible", "statusBarVisible", "toolBarVisible", "locationBarVisible", "scrollbarsVisible", "resizable", "fullscreen", "dialog", "additionalFeatures");
	}
	public cef_popup_features_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_popup_features_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_popup_features_t implements Structure.ByValue {
		
	};
}
