package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:43</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_settings_t extends Structure {
	public int size;
	public int single_process;
	public int no_sandbox;
	/** C type : cef_string_t */
	public cef_string_utf16_t browser_subprocess_path;
	public int multi_threaded_message_loop;
	public int windowless_rendering_enabled;
	public int command_line_args_disabled;
	/** C type : cef_string_t */
	public cef_string_utf16_t cache_path;
	/** C type : cef_string_t */
	public cef_string_utf16_t user_data_path;
	public int persist_session_cookies;
	public int persist_user_preferences;
	/** C type : cef_string_t */
	public cef_string_utf16_t user_agent;
	/** C type : cef_string_t */
	public cef_string_utf16_t product_version;
	/** C type : cef_string_t */
	public cef_string_utf16_t locale;
	/** C type : cef_string_t */
	public cef_string_utf16_t log_file;
	/**
	 * @see cef_log_severity_t<br>
	 * C type : cef_log_severity_t
	 */
	public int log_severity;
	/** C type : cef_string_t */
	public cef_string_utf16_t javascript_flags;
	/** C type : cef_string_t */
	public cef_string_utf16_t resources_dir_path;
	/** C type : cef_string_t */
	public cef_string_utf16_t locales_dir_path;
	public int pack_loading_disabled;
	public int remote_debugging_port;
	public int uncaught_exception_stack_size;
	public int context_safety_implementation;
	public int ignore_certificate_errors;
	/** C type : cef_color_t */
	public int background_color;
	/** C type : cef_string_t */
	public cef_string_utf16_t accept_language_list;
	public cef_settings_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("size", "single_process", "no_sandbox", "browser_subprocess_path", "multi_threaded_message_loop", "windowless_rendering_enabled", "command_line_args_disabled", "cache_path", "user_data_path", "persist_session_cookies", "persist_user_preferences", "user_agent", "product_version", "locale", "log_file", "log_severity", "javascript_flags", "resources_dir_path", "locales_dir_path", "pack_loading_disabled", "remote_debugging_port", "uncaught_exception_stack_size", "context_safety_implementation", "ignore_certificate_errors", "background_color", "accept_language_list");
	}
	public cef_settings_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_settings_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_settings_t implements Structure.ByValue {
		
	};
}
