package cef;
import cef.CefLibrary._cef_print_settings_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_print_handler_capi.h:7</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_print_dialog_callback_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : cont_callback* */
	public cef.cef_request_callback_t.cont_callback cont;
	/** C type : cancel_callback* */
	public cef.cef_urlrequest_t.cancel_callback cancel;
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:5</i> */
	public interface cont_callback extends Callback {
		void apply(cef_print_dialog_callback_t self, _cef_print_settings_t settings);
	};
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:6</i> */
	public interface cancel_callback extends Callback {
		void apply(cef_print_dialog_callback_t self);
	};
	public cef_print_dialog_callback_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "cont", "cancel");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param cont C type : cont_callback*<br>
	 * @param cancel C type : cancel_callback*
	 */
	public cef_print_dialog_callback_t(cef_base_t base, cef.cef_request_callback_t.cont_callback cont, cef.cef_urlrequest_t.cancel_callback cancel) {
		super();
		this.base = base;
		this.cont = cont;
		this.cancel = cancel;
	}
	public cef_print_dialog_callback_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_print_dialog_callback_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_print_dialog_callback_t implements Structure.ByValue {
		
	};
}
