package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_drag_handler_capi.h:7</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_drag_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_drag_enter_callback* */
	public cef_drag_handler_t.on_drag_enter_callback on_drag_enter;
	/** C type : on_draggable_regions_changed_callback* */
	public cef_drag_handler_t.on_draggable_regions_changed_callback on_draggable_regions_changed;
	/** <i>native declaration : include\capi\cef_drag_handler_capi.h:5</i> */
	public interface on_drag_enter_callback extends Callback {
		int apply(cef_drag_handler_t self, cef_browser_t browser, cef_drag_data_t dragData, int mask);
	};
	/** <i>native declaration : include\capi\cef_drag_handler_capi.h:6</i> */
	public interface on_draggable_regions_changed_callback extends Callback {
		void apply(cef_drag_handler_t self, cef_browser_t browser, int regionsCount, cef_draggable_region_t regions);
	};
	public cef_drag_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_drag_enter", "on_draggable_regions_changed");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_drag_enter C type : on_drag_enter_callback*<br>
	 * @param on_draggable_regions_changed C type : on_draggable_regions_changed_callback*
	 */
	public cef_drag_handler_t(cef_base_t base, cef_drag_handler_t.on_drag_enter_callback on_drag_enter, cef_drag_handler_t.on_draggable_regions_changed_callback on_draggable_regions_changed) {
		super();
		this.base = base;
		this.on_drag_enter = on_drag_enter;
		this.on_draggable_regions_changed = on_draggable_regions_changed;
	}
	public cef_drag_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_drag_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_drag_handler_t implements Structure.ByValue {
		
	};
}
