package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_response_filter_capi.h:8</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_response_filter_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : init_filter_callback* */
	public cef_response_filter_t.init_filter_callback init_filter;
	/** <i>native declaration : include\capi\cef_response_filter_capi.h:6</i> */
	public interface init_filter_callback extends Callback {
		int apply(cef_response_filter_t self);
	};
	/** <i>native declaration : include\capi\cef_response_filter_capi.h:7</i> */
	public interface cef_response_filter_status_t_callback extends Callback {
		int apply(cef_response_filter_t self, Pointer data_in, int data_in_size, IntByReference data_in_read, Pointer data_out, int data_out_size, IntByReference data_out_written);
	};
	public cef_response_filter_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "init_filter");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param init_filter C type : init_filter_callback*
	 */
	public cef_response_filter_t(cef_base_t base, cef_response_filter_t.init_filter_callback init_filter) {
		super();
		this.base = base;
		this.init_filter = init_filter;
	}
	public cef_response_filter_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_response_filter_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_response_filter_t implements Structure.ByValue {
		
	};
}
