package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_request_context_handler_capi.h:7</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_request_context_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_cookie_manager_callback* */
	public cef_request_context_handler_t.get_cookie_manager_callback get_cookie_manager;
	/** C type : on_before_plugin_load_callback* */
	public cef_request_context_handler_t.on_before_plugin_load_callback on_before_plugin_load;
	/** <i>native declaration : include\capi\cef_request_context_handler_capi.h:5</i> */
	public interface get_cookie_manager_callback extends Callback {
		cef_cookie_manager_t apply(cef_request_context_handler_t self);
	};
	/** <i>native declaration : include\capi\cef_request_context_handler_capi.h:6</i> */
	public interface on_before_plugin_load_callback extends Callback {
		int apply(cef_request_context_handler_t self, cef_string_utf16_t mime_type, cef_string_utf16_t plugin_url, cef_string_utf16_t top_origin_url, cef_web_plugin_info_t plugin_info, IntByReference plugin_policy);
	};
	public cef_request_context_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_cookie_manager", "on_before_plugin_load");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param get_cookie_manager C type : get_cookie_manager_callback*<br>
	 * @param on_before_plugin_load C type : on_before_plugin_load_callback*
	 */
	public cef_request_context_handler_t(cef_base_t base, cef_request_context_handler_t.get_cookie_manager_callback get_cookie_manager, cef_request_context_handler_t.on_before_plugin_load_callback on_before_plugin_load) {
		super();
		this.base = base;
		this.get_cookie_manager = get_cookie_manager;
		this.on_before_plugin_load = on_before_plugin_load;
	}
	public cef_request_context_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_request_context_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_request_context_handler_t implements Structure.ByValue {
		
	};
}
