package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_context_menu_handler_capi.h:74</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_context_menu_params_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_xcoord_callback* */
	public cef_context_menu_params_t.get_xcoord_callback get_xcoord;
	/** C type : get_ycoord_callback* */
	public cef_context_menu_params_t.get_ycoord_callback get_ycoord;
	/** C type : has_image_contents_callback* */
	public cef_context_menu_params_t.has_image_contents_callback has_image_contents;
	/** C type : get_dictionary_suggestions_callback* */
	public cef_context_menu_params_t.get_dictionary_suggestions_callback get_dictionary_suggestions;
	/** C type : is_editable_callback* */
	public cef_context_menu_params_t.is_editable_callback is_editable;
	/** C type : is_spell_check_enabled_callback* */
	public cef_context_menu_params_t.is_spell_check_enabled_callback is_spell_check_enabled;
	/** C type : is_custom_menu_callback* */
	public cef_context_menu_params_t.is_custom_menu_callback is_custom_menu;
	/** C type : is_pepper_menu_callback* */
	public cef_context_menu_params_t.is_pepper_menu_callback is_pepper_menu;
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:54</i> */
	public interface get_xcoord_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:55</i> */
	public interface get_ycoord_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:56</i> */
	public interface cef_context_menu_type_flags_t_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:57</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:58</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:59</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:60</i> */
	public interface has_image_contents_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:61</i> */
	public interface cef_string_userfree_t_callback4 extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:62</i> */
	public interface cef_string_userfree_t_callback5 extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:63</i> */
	public interface cef_string_userfree_t_callback6 extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:64</i> */
	public interface cef_context_menu_media_type_t_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:65</i> */
	public interface cef_context_menu_media_state_flags_t_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:66</i> */
	public interface cef_string_userfree_t_callback7 extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:67</i> */
	public interface cef_string_userfree_t_callback8 extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:68</i> */
	public interface get_dictionary_suggestions_callback extends Callback {
		int apply(cef_context_menu_params_t self, Pointer suggestions);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:69</i> */
	public interface is_editable_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:70</i> */
	public interface is_spell_check_enabled_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:71</i> */
	public interface cef_context_menu_edit_state_flags_t_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:72</i> */
	public interface is_custom_menu_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	/** <i>native declaration : include\capi\cef_context_menu_handler_capi.h:73</i> */
	public interface is_pepper_menu_callback extends Callback {
		int apply(cef_context_menu_params_t self);
	};
	public cef_context_menu_params_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_xcoord", "get_ycoord", "has_image_contents", "get_dictionary_suggestions", "is_editable", "is_spell_check_enabled", "is_custom_menu", "is_pepper_menu");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param get_xcoord C type : get_xcoord_callback*<br>
	 * @param get_ycoord C type : get_ycoord_callback*<br>
	 * @param has_image_contents C type : has_image_contents_callback*<br>
	 * @param get_dictionary_suggestions C type : get_dictionary_suggestions_callback*<br>
	 * @param is_editable C type : is_editable_callback*<br>
	 * @param is_spell_check_enabled C type : is_spell_check_enabled_callback*<br>
	 * @param is_custom_menu C type : is_custom_menu_callback*<br>
	 * @param is_pepper_menu C type : is_pepper_menu_callback*
	 */
	public cef_context_menu_params_t(cef_base_t base, cef_context_menu_params_t.get_xcoord_callback get_xcoord, cef_context_menu_params_t.get_ycoord_callback get_ycoord, cef_context_menu_params_t.has_image_contents_callback has_image_contents, cef_context_menu_params_t.get_dictionary_suggestions_callback get_dictionary_suggestions, cef_context_menu_params_t.is_editable_callback is_editable, cef_context_menu_params_t.is_spell_check_enabled_callback is_spell_check_enabled, cef_context_menu_params_t.is_custom_menu_callback is_custom_menu, cef_context_menu_params_t.is_pepper_menu_callback is_pepper_menu) {
		super();
		this.base = base;
		this.get_xcoord = get_xcoord;
		this.get_ycoord = get_ycoord;
		this.has_image_contents = has_image_contents;
		this.get_dictionary_suggestions = get_dictionary_suggestions;
		this.is_editable = is_editable;
		this.is_spell_check_enabled = is_spell_check_enabled;
		this.is_custom_menu = is_custom_menu;
		this.is_pepper_menu = is_pepper_menu;
	}
	public cef_context_menu_params_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_context_menu_params_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_context_menu_params_t implements Structure.ByValue {
		
	};
}
