package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:331</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_insets_t extends Structure {
	public int top;
	public int left;
	public int bottom;
	public int right;
	public cef_insets_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("top", "left", "bottom", "right");
	}
	public cef_insets_t(int top, int left, int bottom, int right) {
		super();
		this.top = top;
		this.left = left;
		this.bottom = bottom;
		this.right = right;
	}
	public cef_insets_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_insets_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_insets_t implements Structure.ByValue {
		
	};
}
