package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:760</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_pdf_print_settings_t extends Structure {
	/** C type : cef_string_t */
	public cef_string_utf16_t header_footer_title;
	/** C type : cef_string_t */
	public cef_string_utf16_t header_footer_url;
	public int page_width;
	public int page_height;
	public double margin_top;
	public double margin_right;
	public double margin_bottom;
	public double margin_left;
	/**
	 * @see cef_pdf_print_margin_type_t<br>
	 * C type : cef_pdf_print_margin_type_t
	 */
	public int margin_type;
	public int header_footer_enabled;
	public int selection_only;
	public int landscape;
	public int backgrounds_enabled;
	public cef_pdf_print_settings_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("header_footer_title", "header_footer_url", "page_width", "page_height", "margin_top", "margin_right", "margin_bottom", "margin_left", "margin_type", "header_footer_enabled", "selection_only", "landscape", "backgrounds_enabled");
	}
	public cef_pdf_print_settings_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_pdf_print_settings_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_pdf_print_settings_t implements Structure.ByValue {
		
	};
}
