package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:496</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_key_event_t extends Structure {
	/**
	 * @see cef_key_event_type_t<br>
	 * C type : cef_key_event_type_t
	 */
	public int type;
	public int modifiers;
	public int windows_key_code;
	public int native_key_code;
	public int is_system_key;
	public short character;
	public short unmodified_character;
	public int focus_on_editable_field;
	public cef_key_event_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("type", "modifiers", "windows_key_code", "native_key_code", "is_system_key", "character", "unmodified_character", "focus_on_editable_field");
	}
	/**
	 * @param type @see cef_key_event_type_t<br>
	 * C type : cef_key_event_type_t
	 */
	public cef_key_event_t(int type, int modifiers, int windows_key_code, int native_key_code, int is_system_key, short character, short unmodified_character, int focus_on_editable_field) {
		super();
		this.type = type;
		this.modifiers = modifiers;
		this.windows_key_code = windows_key_code;
		this.native_key_code = native_key_code;
		this.is_system_key = is_system_key;
		this.character = character;
		this.unmodified_character = unmodified_character;
		this.focus_on_editable_field = focus_on_editable_field;
	}
	public cef_key_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_key_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_key_event_t implements Structure.ByValue {
		
	};
}
