package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:617</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_geoposition_t extends Structure {
	public double latitude;
	public double longitude;
	public double altitude;
	public double accuracy;
	public double altitude_accuracy;
	public double heading;
	public double speed;
	/** C type : cef_time_t */
	public cef_time_t timestamp;
	/**
	 * @see cef_geoposition_error_code_t<br>
	 * C type : cef_geoposition_error_code_t
	 */
	public int error_code;
	/** C type : cef_string_t */
	public cef_string_utf16_t error_message;
	public cef_geoposition_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("latitude", "longitude", "altitude", "accuracy", "altitude_accuracy", "heading", "speed", "timestamp", "error_code", "error_message");
	}
	public cef_geoposition_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_geoposition_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_geoposition_t implements Structure.ByValue {
		
	};
}
