package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_urlrequest_capi.h:33</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_urlrequest_client_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_request_complete_callback* */
	public cef_urlrequest_client_t.on_request_complete_callback on_request_complete;
	/** C type : on_upload_progress_callback* */
	public cef_urlrequest_client_t.on_upload_progress_callback on_upload_progress;
	/** C type : on_download_progress_callback* */
	public cef_urlrequest_client_t.on_download_progress_callback on_download_progress;
	/** C type : on_download_data_callback* */
	public cef_urlrequest_client_t.on_download_data_callback on_download_data;
	/** C type : get_auth_credentials_callback* */
	public cef_urlrequest_client_t.get_auth_credentials_callback get_auth_credentials;
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:28</i> */
	public interface on_request_complete_callback extends Callback {
		void apply(cef_urlrequest_client_t self, cef_urlrequest_t request);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:29</i> */
	public interface on_upload_progress_callback extends Callback {
		void apply(cef_urlrequest_client_t self, cef_urlrequest_t request, long current, long total);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:30</i> */
	public interface on_download_progress_callback extends Callback {
		void apply(cef_urlrequest_client_t self, cef_urlrequest_t request, long current, long total);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:31</i> */
	public interface on_download_data_callback extends Callback {
		void apply(cef_urlrequest_client_t self, cef_urlrequest_t request, Pointer data, int data_length);
	};
	/** <i>native declaration : include\capi\cef_urlrequest_capi.h:32</i> */
	public interface get_auth_credentials_callback extends Callback {
		int apply(cef_urlrequest_client_t self, int isProxy, cef_string_utf16_t host, int port, cef_string_utf16_t realm, cef_string_utf16_t scheme, cef_auth_callback_t callback);
	};
	public cef_urlrequest_client_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_request_complete", "on_upload_progress", "on_download_progress", "on_download_data", "get_auth_credentials");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_request_complete C type : on_request_complete_callback*<br>
	 * @param on_upload_progress C type : on_upload_progress_callback*<br>
	 * @param on_download_progress C type : on_download_progress_callback*<br>
	 * @param on_download_data C type : on_download_data_callback*<br>
	 * @param get_auth_credentials C type : get_auth_credentials_callback*
	 */
	public cef_urlrequest_client_t(cef_base_t base, cef_urlrequest_client_t.on_request_complete_callback on_request_complete, cef_urlrequest_client_t.on_upload_progress_callback on_upload_progress, cef_urlrequest_client_t.on_download_progress_callback on_download_progress, cef_urlrequest_client_t.on_download_data_callback on_download_data, cef_urlrequest_client_t.get_auth_credentials_callback get_auth_credentials) {
		super();
		this.base = base;
		this.on_request_complete = on_request_complete;
		this.on_upload_progress = on_upload_progress;
		this.on_download_progress = on_download_progress;
		this.on_download_data = on_download_data;
		this.get_auth_credentials = get_auth_credentials;
	}
	public cef_urlrequest_client_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_urlrequest_client_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_urlrequest_client_t implements Structure.ByValue {
		
	};
}
