package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_drag_data_capi.h:54</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_drag_data_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : clone_callback* */
	public cef_drag_data_t.clone_callback clone$;
	/** C type : is_read_only_callback* */
	public cef.cef_response_t.is_read_only_callback is_read_only;
	/** C type : is_link_callback* */
	public cef_drag_data_t.is_link_callback is_link;
	/** C type : is_fragment_callback* */
	public cef_drag_data_t.is_fragment_callback is_fragment;
	/** C type : is_file_callback* */
	public cef_drag_data_t.is_file_callback is_file;
	/** C type : get_file_contents_callback* */
	public cef_drag_data_t.get_file_contents_callback get_file_contents;
	/** C type : get_file_names_callback* */
	public cef_drag_data_t.get_file_names_callback get_file_names;
	/** C type : set_link_url_callback* */
	public cef_drag_data_t.set_link_url_callback set_link_url;
	/** C type : set_link_title_callback* */
	public cef_drag_data_t.set_link_title_callback set_link_title;
	/** C type : set_link_metadata_callback* */
	public cef_drag_data_t.set_link_metadata_callback set_link_metadata;
	/** C type : set_fragment_text_callback* */
	public cef_drag_data_t.set_fragment_text_callback set_fragment_text;
	/** C type : set_fragment_html_callback* */
	public cef_drag_data_t.set_fragment_html_callback set_fragment_html;
	/** C type : set_fragment_base_url_callback* */
	public cef_drag_data_t.set_fragment_base_url_callback set_fragment_base_url;
	/** C type : reset_file_contents_callback* */
	public cef_drag_data_t.reset_file_contents_callback reset_file_contents;
	/** C type : add_file_callback* */
	public cef_drag_data_t.add_file_callback add_file;
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:32</i> */
	public interface clone_callback extends Callback {
		cef_drag_data_t apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:33</i> */
	public interface is_read_only_callback extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:34</i> */
	public interface is_link_callback extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:35</i> */
	public interface is_fragment_callback extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:36</i> */
	public interface is_file_callback extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:37</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:38</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:39</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:40</i> */
	public interface cef_string_userfree_t_callback4 extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:41</i> */
	public interface cef_string_userfree_t_callback5 extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:42</i> */
	public interface cef_string_userfree_t_callback6 extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:43</i> */
	public interface cef_string_userfree_t_callback7 extends Callback {
		int apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:44</i> */
	public interface get_file_contents_callback extends Callback {
		int apply(cef_drag_data_t self, cef_stream_writer_t writer);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:45</i> */
	public interface get_file_names_callback extends Callback {
		int apply(cef_drag_data_t self, Pointer names);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:46</i> */
	public interface set_link_url_callback extends Callback {
		void apply(cef_drag_data_t self, cef_string_utf16_t url);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:47</i> */
	public interface set_link_title_callback extends Callback {
		void apply(cef_drag_data_t self, cef_string_utf16_t title);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:48</i> */
	public interface set_link_metadata_callback extends Callback {
		void apply(cef_drag_data_t self, cef_string_utf16_t data);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:49</i> */
	public interface set_fragment_text_callback extends Callback {
		void apply(cef_drag_data_t self, cef_string_utf16_t text);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:50</i> */
	public interface set_fragment_html_callback extends Callback {
		void apply(cef_drag_data_t self, cef_string_utf16_t html);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:51</i> */
	public interface set_fragment_base_url_callback extends Callback {
		void apply(cef_drag_data_t self, cef_string_utf16_t base_url);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:52</i> */
	public interface reset_file_contents_callback extends Callback {
		void apply(cef_drag_data_t self);
	};
	/** <i>native declaration : include\capi\cef_drag_data_capi.h:53</i> */
	public interface add_file_callback extends Callback {
		void apply(cef_drag_data_t self, cef_string_utf16_t path, cef_string_utf16_t display_name);
	};
	public cef_drag_data_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "clone$", "is_read_only", "is_link", "is_fragment", "is_file", "get_file_contents", "get_file_names", "set_link_url", "set_link_title", "set_link_metadata", "set_fragment_text", "set_fragment_html", "set_fragment_base_url", "reset_file_contents", "add_file");
	}
	public cef_drag_data_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_drag_data_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_drag_data_t implements Structure.ByValue {
		
	};
}
