package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_v8_capi.h:65</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_v8exception_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_line_number_callback* */
	public cef.cef_xml_reader_t.get_line_number_callback get_line_number;
	/** C type : get_start_position_callback* */
	public cef_v8exception_t.get_start_position_callback get_start_position;
	/** C type : get_end_position_callback* */
	public cef_v8exception_t.get_end_position_callback get_end_position;
	/** C type : get_start_column_callback* */
	public cef_v8exception_t.get_start_column_callback get_start_column;
	/** C type : get_end_column_callback* */
	public cef_v8exception_t.get_end_column_callback get_end_column;
	/** <i>native declaration : include\capi\cef_v8_capi.h:57</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_v8exception_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:58</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_v8exception_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:59</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_v8exception_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:60</i> */
	public interface get_line_number_callback extends Callback {
		int apply(cef_v8exception_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:61</i> */
	public interface get_start_position_callback extends Callback {
		int apply(cef_v8exception_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:62</i> */
	public interface get_end_position_callback extends Callback {
		int apply(cef_v8exception_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:63</i> */
	public interface get_start_column_callback extends Callback {
		int apply(cef_v8exception_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:64</i> */
	public interface get_end_column_callback extends Callback {
		int apply(cef_v8exception_t self);
	};
	public cef_v8exception_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_line_number", "get_start_position", "get_end_position", "get_start_column", "get_end_column");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param get_line_number C type : get_line_number_callback*<br>
	 * @param get_start_position C type : get_start_position_callback*<br>
	 * @param get_end_position C type : get_end_position_callback*<br>
	 * @param get_start_column C type : get_start_column_callback*<br>
	 * @param get_end_column C type : get_end_column_callback*
	 */
	public cef_v8exception_t(cef_base_t base, cef.cef_xml_reader_t.get_line_number_callback get_line_number, cef_v8exception_t.get_start_position_callback get_start_position, cef_v8exception_t.get_end_position_callback get_end_position, cef_v8exception_t.get_start_column_callback get_start_column, cef_v8exception_t.get_end_column_callback get_end_column) {
		super();
		this.base = base;
		this.get_line_number = get_line_number;
		this.get_start_position = get_start_position;
		this.get_end_position = get_end_position;
		this.get_start_column = get_start_column;
		this.get_end_column = get_end_column;
	}
	public cef_v8exception_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_v8exception_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_v8exception_t implements Structure.ByValue {
		
	};
}
