package cef;
import cef.CefLibrary.HINSTANCE;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types_win.h:3</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_main_args_t extends Structure {
	/** C type : HINSTANCE */
	public HINSTANCE instance;
	public cef_main_args_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("instance");
	}
	/** @param instance C type : HINSTANCE */
	public cef_main_args_t(HINSTANCE instance) {
		super();
		this.instance = instance;
	}
	public cef_main_args_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_main_args_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_main_args_t implements Structure.ByValue {
		
	};
}
