package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_dom_capi.h:44</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_domdocument_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_document_callback* */
	public cef_domnode_t.get_document_callback get_document;
	/** C type : get_body_callback* */
	public cef_domdocument_t.get_body_callback get_body;
	/** C type : get_head_callback* */
	public cef_domdocument_t.get_head_callback get_head;
	/** C type : get_element_by_id_callback* */
	public cef_domdocument_t.get_element_by_id_callback get_element_by_id;
	/** C type : get_focused_node_callback* */
	public cef_domdocument_t.get_focused_node_callback get_focused_node;
	/** C type : has_selection_callback* */
	public cef_domdocument_t.has_selection_callback has_selection;
	/** C type : get_selection_start_offset_callback* */
	public cef_domdocument_t.get_selection_start_offset_callback get_selection_start_offset;
	/** C type : get_selection_end_offset_callback* */
	public cef_domdocument_t.get_selection_end_offset_callback get_selection_end_offset;
	/** <i>native declaration : include\capi\cef_dom_capi.h:30</i> */
	public interface cef_dom_document_type_t_callback extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:31</i> */
	public interface get_document_callback extends Callback {
		cef_domnode_t apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:32</i> */
	public interface get_body_callback extends Callback {
		cef_domnode_t apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:33</i> */
	public interface get_head_callback extends Callback {
		cef_domnode_t apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:34</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:35</i> */
	public interface get_element_by_id_callback extends Callback {
		cef_domnode_t apply(cef_domdocument_t self, cef_string_utf16_t id);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:36</i> */
	public interface get_focused_node_callback extends Callback {
		cef_domnode_t apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:37</i> */
	public interface has_selection_callback extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:38</i> */
	public interface get_selection_start_offset_callback extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:39</i> */
	public interface get_selection_end_offset_callback extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:40</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:41</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:42</i> */
	public interface cef_string_userfree_t_callback4 extends Callback {
		int apply(cef_domdocument_t self);
	};
	/** <i>native declaration : include\capi\cef_dom_capi.h:43</i> */
	public interface cef_string_userfree_t_callback5 extends Callback {
		int apply(cef_domdocument_t self, cef_string_utf16_t partialURL);
	};
	public cef_domdocument_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_document", "get_body", "get_head", "get_element_by_id", "get_focused_node", "has_selection", "get_selection_start_offset", "get_selection_end_offset");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param get_document C type : get_document_callback*<br>
	 * @param get_body C type : get_body_callback*<br>
	 * @param get_head C type : get_head_callback*<br>
	 * @param get_element_by_id C type : get_element_by_id_callback*<br>
	 * @param get_focused_node C type : get_focused_node_callback*<br>
	 * @param has_selection C type : has_selection_callback*<br>
	 * @param get_selection_start_offset C type : get_selection_start_offset_callback*<br>
	 * @param get_selection_end_offset C type : get_selection_end_offset_callback*
	 */
	public cef_domdocument_t(cef_base_t base, cef_domnode_t.get_document_callback get_document, cef_domdocument_t.get_body_callback get_body, cef_domdocument_t.get_head_callback get_head, cef_domdocument_t.get_element_by_id_callback get_element_by_id, cef_domdocument_t.get_focused_node_callback get_focused_node, cef_domdocument_t.has_selection_callback has_selection, cef_domdocument_t.get_selection_start_offset_callback get_selection_start_offset, cef_domdocument_t.get_selection_end_offset_callback get_selection_end_offset) {
		super();
		this.base = base;
		this.get_document = get_document;
		this.get_body = get_body;
		this.get_head = get_head;
		this.get_element_by_id = get_element_by_id;
		this.get_focused_node = get_focused_node;
		this.has_selection = has_selection;
		this.get_selection_start_offset = get_selection_start_offset;
		this.get_selection_end_offset = get_selection_end_offset;
	}
	public cef_domdocument_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_domdocument_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_domdocument_t implements Structure.ByValue {
		
	};
}
