package cef;
import cef.CefLibrary._cef_frame_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_request_handler_capi.h:41</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_request_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_before_browse_callback* */
	public cef_request_handler_t.on_before_browse_callback on_before_browse;
	/** C type : on_open_urlfrom_tab_callback* */
	public cef_request_handler_t.on_open_urlfrom_tab_callback on_open_urlfrom_tab;
	/** C type : get_resource_handler_callback* */
	public cef_request_handler_t.get_resource_handler_callback get_resource_handler;
	/** C type : on_resource_redirect_callback* */
	public cef_request_handler_t.on_resource_redirect_callback on_resource_redirect;
	/** C type : on_resource_response_callback* */
	public cef_request_handler_t.on_resource_response_callback on_resource_response;
	/** C type : get_resource_response_filter_callback* */
	public cef_request_handler_t.get_resource_response_filter_callback get_resource_response_filter;
	/** C type : on_resource_load_complete_callback* */
	public cef_request_handler_t.on_resource_load_complete_callback on_resource_load_complete;
	/** C type : get_auth_credentials_callback* */
	public cef.cef_urlrequest_client_t.get_auth_credentials_callback get_auth_credentials;
	/** C type : on_quota_request_callback* */
	public cef_request_handler_t.on_quota_request_callback on_quota_request;
	/** C type : on_protocol_execution_callback* */
	public cef_request_handler_t.on_protocol_execution_callback on_protocol_execution;
	/** C type : on_certificate_error_callback* */
	public cef_request_handler_t.on_certificate_error_callback on_certificate_error;
	/** C type : on_plugin_crashed_callback* */
	public cef_request_handler_t.on_plugin_crashed_callback on_plugin_crashed;
	/** C type : on_render_view_ready_callback* */
	public cef_request_handler_t.on_render_view_ready_callback on_render_view_ready;
	/** C type : on_render_process_terminated_callback* */
	public cef_request_handler_t.on_render_process_terminated_callback on_render_process_terminated;
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:26</i> */
	public interface on_before_browse_callback extends Callback {
		int apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_request_t request, int is_redirect);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:27</i> */
	public interface on_open_urlfrom_tab_callback extends Callback {
		int apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_string_utf16_t target_url, int target_disposition, int user_gesture);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:28</i> */
	public interface cef_return_value_t_callback extends Callback {
		int apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_request_t request, cef_request_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:29</i> */
	public interface get_resource_handler_callback extends Callback {
		cef_resource_handler_t apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_request_t request);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:30</i> */
	public interface on_resource_redirect_callback extends Callback {
		void apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_request_t request, cef_string_utf16_t new_url);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:31</i> */
	public interface on_resource_response_callback extends Callback {
		int apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_request_t request, cef_response_t response);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:32</i> */
	public interface get_resource_response_filter_callback extends Callback {
		cef_response_filter_t apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_request_t request, cef_response_t response);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:33</i> */
	public interface on_resource_load_complete_callback extends Callback {
		void apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, cef_request_t request, cef_response_t response, int status, long received_content_length);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:34</i> */
	public interface get_auth_credentials_callback extends Callback {
		int apply(cef_request_handler_t self, cef_browser_t browser, _cef_frame_t frame, int isProxy, cef_string_utf16_t host, int port, cef_string_utf16_t realm, cef_string_utf16_t scheme, cef_auth_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:35</i> */
	public interface on_quota_request_callback extends Callback {
		int apply(cef_request_handler_t self, cef_browser_t browser, cef_string_utf16_t origin_url, long new_size, cef_request_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:36</i> */
	public interface on_protocol_execution_callback extends Callback {
		void apply(cef_request_handler_t self, cef_browser_t browser, cef_string_utf16_t url, IntByReference allow_os_execution);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:37</i> */
	public interface on_certificate_error_callback extends Callback {
		int apply(cef_request_handler_t self, cef_browser_t browser, int cert_error, cef_string_utf16_t request_url, cef_sslinfo_t ssl_info, cef_request_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:38</i> */
	public interface on_plugin_crashed_callback extends Callback {
		void apply(cef_request_handler_t self, cef_browser_t browser, cef_string_utf16_t plugin_path);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:39</i> */
	public interface on_render_view_ready_callback extends Callback {
		void apply(cef_request_handler_t self, cef_browser_t browser);
	};
	/** <i>native declaration : include\capi\cef_request_handler_capi.h:40</i> */
	public interface on_render_process_terminated_callback extends Callback {
		void apply(cef_request_handler_t self, cef_browser_t browser, int status);
	};
	public cef_request_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_before_browse", "on_open_urlfrom_tab", "get_resource_handler", "on_resource_redirect", "on_resource_response", "get_resource_response_filter", "on_resource_load_complete", "get_auth_credentials", "on_quota_request", "on_protocol_execution", "on_certificate_error", "on_plugin_crashed", "on_render_view_ready", "on_render_process_terminated");
	}
	public cef_request_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_request_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_request_handler_t implements Structure.ByValue {
		
	};
}
