package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_ssl_info_capi.h:26</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_sslcert_principal_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_street_addresses_callback* */
	public cef_sslcert_principal_t.get_street_addresses_callback get_street_addresses;
	/** C type : get_organization_names_callback* */
	public cef_sslcert_principal_t.get_organization_names_callback get_organization_names;
	/** C type : get_organization_unit_names_callback* */
	public cef_sslcert_principal_t.get_organization_unit_names_callback get_organization_unit_names;
	/** C type : get_domain_components_callback* */
	public cef_sslcert_principal_t.get_domain_components_callback get_domain_components;
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:17</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_sslcert_principal_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:18</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_sslcert_principal_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:19</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_sslcert_principal_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:20</i> */
	public interface cef_string_userfree_t_callback4 extends Callback {
		int apply(cef_sslcert_principal_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:21</i> */
	public interface cef_string_userfree_t_callback5 extends Callback {
		int apply(cef_sslcert_principal_t self);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:22</i> */
	public interface get_street_addresses_callback extends Callback {
		void apply(cef_sslcert_principal_t self, Pointer addresses);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:23</i> */
	public interface get_organization_names_callback extends Callback {
		void apply(cef_sslcert_principal_t self, Pointer names);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:24</i> */
	public interface get_organization_unit_names_callback extends Callback {
		void apply(cef_sslcert_principal_t self, Pointer names);
	};
	/** <i>native declaration : include\capi\cef_ssl_info_capi.h:25</i> */
	public interface get_domain_components_callback extends Callback {
		void apply(cef_sslcert_principal_t self, Pointer components);
	};
	public cef_sslcert_principal_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_street_addresses", "get_organization_names", "get_organization_unit_names", "get_domain_components");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param get_street_addresses C type : get_street_addresses_callback*<br>
	 * @param get_organization_names C type : get_organization_names_callback*<br>
	 * @param get_organization_unit_names C type : get_organization_unit_names_callback*<br>
	 * @param get_domain_components C type : get_domain_components_callback*
	 */
	public cef_sslcert_principal_t(cef_base_t base, cef_sslcert_principal_t.get_street_addresses_callback get_street_addresses, cef_sslcert_principal_t.get_organization_names_callback get_organization_names, cef_sslcert_principal_t.get_organization_unit_names_callback get_organization_unit_names, cef_sslcert_principal_t.get_domain_components_callback get_domain_components) {
		super();
		this.base = base;
		this.get_street_addresses = get_street_addresses;
		this.get_organization_names = get_organization_names;
		this.get_organization_unit_names = get_organization_unit_names;
		this.get_domain_components = get_domain_components;
	}
	public cef_sslcert_principal_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_sslcert_principal_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_sslcert_principal_t implements Structure.ByValue {
		
	};
}
