package cef;
import cef.CefLibrary._cef_print_settings_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_print_handler_capi.h:28</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_print_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_print_start_callback* */
	public cef_print_handler_t.on_print_start_callback on_print_start;
	/** C type : on_print_settings_callback* */
	public cef_print_handler_t.on_print_settings_callback on_print_settings;
	/** C type : on_print_dialog_callback* */
	public cef_print_handler_t.on_print_dialog_callback on_print_dialog;
	/** C type : on_print_job_callback* */
	public cef_print_handler_t.on_print_job_callback on_print_job;
	/** C type : on_print_reset_callback* */
	public cef_print_handler_t.on_print_reset_callback on_print_reset;
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:22</i> */
	public interface on_print_start_callback extends Callback {
		void apply(cef_print_handler_t self, cef_browser_t browser);
	};
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:23</i> */
	public interface on_print_settings_callback extends Callback {
		void apply(cef_print_handler_t self, _cef_print_settings_t settings, int get_defaults);
	};
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:24</i> */
	public interface on_print_dialog_callback extends Callback {
		int apply(cef_print_handler_t self, int has_selection, cef_print_dialog_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:25</i> */
	public interface on_print_job_callback extends Callback {
		int apply(cef_print_handler_t self, cef_string_utf16_t document_name, cef_string_utf16_t pdf_file_path, cef_print_job_callback_t callback);
	};
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:26</i> */
	public interface on_print_reset_callback extends Callback {
		void apply(cef_print_handler_t self);
	};
	/** <i>native declaration : include\capi\cef_print_handler_capi.h:27</i> */
	public interface cef_size_t_callback extends Callback {
		int apply(cef_print_handler_t self, int device_units_per_inch);
	};
	public cef_print_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_print_start", "on_print_settings", "on_print_dialog", "on_print_job", "on_print_reset");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_print_start C type : on_print_start_callback*<br>
	 * @param on_print_settings C type : on_print_settings_callback*<br>
	 * @param on_print_dialog C type : on_print_dialog_callback*<br>
	 * @param on_print_job C type : on_print_job_callback*<br>
	 * @param on_print_reset C type : on_print_reset_callback*
	 */
	public cef_print_handler_t(cef_base_t base, cef_print_handler_t.on_print_start_callback on_print_start, cef_print_handler_t.on_print_settings_callback on_print_settings, cef_print_handler_t.on_print_dialog_callback on_print_dialog, cef_print_handler_t.on_print_job_callback on_print_job, cef_print_handler_t.on_print_reset_callback on_print_reset) {
		super();
		this.base = base;
		this.on_print_start = on_print_start;
		this.on_print_settings = on_print_settings;
		this.on_print_dialog = on_print_dialog;
		this.on_print_job = on_print_job;
		this.on_print_reset = on_print_reset;
	}
	public cef_print_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_print_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_print_handler_t implements Structure.ByValue {
		
	};
}
