package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_download_handler_capi.h:14</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_download_item_callback_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : cancel_callback* */
	public cef.cef_urlrequest_t.cancel_callback cancel;
	/** C type : pause_callback* */
	public cef_download_item_callback_t.pause_callback pause;
	/** C type : resume_callback* */
	public cef_download_item_callback_t.resume_callback resume;
	/** <i>native declaration : include\capi\cef_download_handler_capi.h:11</i> */
	public interface cancel_callback extends Callback {
		void apply(cef_download_item_callback_t self);
	};
	/** <i>native declaration : include\capi\cef_download_handler_capi.h:12</i> */
	public interface pause_callback extends Callback {
		void apply(cef_download_item_callback_t self);
	};
	/** <i>native declaration : include\capi\cef_download_handler_capi.h:13</i> */
	public interface resume_callback extends Callback {
		void apply(cef_download_item_callback_t self);
	};
	public cef_download_item_callback_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "cancel", "pause", "resume");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param cancel C type : cancel_callback*<br>
	 * @param pause C type : pause_callback*<br>
	 * @param resume C type : resume_callback*
	 */
	public cef_download_item_callback_t(cef_base_t base, cef.cef_urlrequest_t.cancel_callback cancel, cef_download_item_callback_t.pause_callback pause, cef_download_item_callback_t.resume_callback resume) {
		super();
		this.base = base;
		this.cancel = cancel;
		this.pause = pause;
		this.resume = resume;
	}
	public cef_download_item_callback_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_download_item_callback_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_download_item_callback_t implements Structure.ByValue {
		
	};
}
