package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_find_handler_capi.h:5</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_find_handler_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_find_result_callback* */
	public cef_find_handler_t.on_find_result_callback on_find_result;
	/** <i>native declaration : include\capi\cef_find_handler_capi.h:4</i> */
	public interface on_find_result_callback extends Callback {
		void apply(cef_find_handler_t self, cef_browser_t browser, int identifier, int count, cef_rect_t selectionRect, int activeMatchOrdinal, int finalUpdate);
	};
	public cef_find_handler_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_find_result");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_find_result C type : on_find_result_callback*
	 */
	public cef_find_handler_t(cef_base_t base, cef_find_handler_t.on_find_result_callback on_find_result) {
		super();
		this.base = base;
		this.on_find_result = on_find_result;
	}
	public cef_find_handler_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_find_handler_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_find_handler_t implements Structure.ByValue {
		
	};
}
