package cef;
import cef.CefLibrary._cef_process_message_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_client_capi.h:33</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_client_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_context_menu_handler_callback* */
	public cef_client_t.get_context_menu_handler_callback get_context_menu_handler;
	/** C type : get_dialog_handler_callback* */
	public cef_client_t.get_dialog_handler_callback get_dialog_handler;
	/** C type : get_display_handler_callback* */
	public cef_client_t.get_display_handler_callback get_display_handler;
	/** C type : get_download_handler_callback* */
	public cef_client_t.get_download_handler_callback get_download_handler;
	/** C type : get_drag_handler_callback* */
	public cef_client_t.get_drag_handler_callback get_drag_handler;
	/** C type : get_find_handler_callback* */
	public cef_client_t.get_find_handler_callback get_find_handler;
	/** C type : get_focus_handler_callback* */
	public cef_client_t.get_focus_handler_callback get_focus_handler;
	/** C type : get_geolocation_handler_callback* */
	public cef_client_t.get_geolocation_handler_callback get_geolocation_handler;
	/** C type : get_jsdialog_handler_callback* */
	public cef_client_t.get_jsdialog_handler_callback get_jsdialog_handler;
	/** C type : get_keyboard_handler_callback* */
	public cef_client_t.get_keyboard_handler_callback get_keyboard_handler;
	/** C type : get_life_span_handler_callback* */
	public cef_client_t.get_life_span_handler_callback get_life_span_handler;
	/** C type : get_load_handler_callback* */
	public cef_client_t.get_load_handler_callback get_load_handler;
	/** C type : get_render_handler_callback* */
	public cef_client_t.get_render_handler_callback get_render_handler;
	/** C type : get_request_handler_callback* */
	public cef_client_t.get_request_handler_callback get_request_handler;
	/** C type : on_process_message_received_callback* */
	public cef_client_t.on_process_message_received_callback on_process_message_received;
	/** <i>native declaration : include\capi\cef_client_capi.h:18</i> */
	public interface get_context_menu_handler_callback extends Callback {
		cef_context_menu_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:19</i> */
	public interface get_dialog_handler_callback extends Callback {
		cef_dialog_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:20</i> */
	public interface get_display_handler_callback extends Callback {
		cef_display_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:21</i> */
	public interface get_download_handler_callback extends Callback {
		cef_download_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:22</i> */
	public interface get_drag_handler_callback extends Callback {
		cef_drag_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:23</i> */
	public interface get_find_handler_callback extends Callback {
		cef_find_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:24</i> */
	public interface get_focus_handler_callback extends Callback {
		cef_focus_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:25</i> */
	public interface get_geolocation_handler_callback extends Callback {
		cef_geolocation_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:26</i> */
	public interface get_jsdialog_handler_callback extends Callback {
		cef_jsdialog_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:27</i> */
	public interface get_keyboard_handler_callback extends Callback {
		cef_keyboard_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:28</i> */
	public interface get_life_span_handler_callback extends Callback {
		cef_life_span_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:29</i> */
	public interface get_load_handler_callback extends Callback {
		cef_load_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:30</i> */
	public interface get_render_handler_callback extends Callback {
		cef_render_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:31</i> */
	public interface get_request_handler_callback extends Callback {
		cef_request_handler_t apply(cef_client_t self);
	};
	/** <i>native declaration : include\capi\cef_client_capi.h:32</i> */
	public interface on_process_message_received_callback extends Callback {
		int apply(cef_client_t self, cef_browser_t browser, int source_process, _cef_process_message_t message);
	};
	public cef_client_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_context_menu_handler", "get_dialog_handler", "get_display_handler", "get_download_handler", "get_drag_handler", "get_find_handler", "get_focus_handler", "get_geolocation_handler", "get_jsdialog_handler", "get_keyboard_handler", "get_life_span_handler", "get_load_handler", "get_render_handler", "get_request_handler", "on_process_message_received");
	}
	public cef_client_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_client_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_client_t implements Structure.ByValue {
		
	};
}
