package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_v8_capi.h:190</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_v8stack_trace_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : is_valid_callback* */
	public cef.cef_download_item_t.is_valid_callback is_valid;
	/** C type : get_frame_count_callback* */
	public cef_v8stack_trace_t.get_frame_count_callback get_frame_count;
	/** C type : get_frame_callback* */
	public cef_v8stack_trace_t.get_frame_callback get_frame;
	/** <i>native declaration : include\capi\cef_v8_capi.h:187</i> */
	public interface is_valid_callback extends Callback {
		int apply(cef_v8stack_trace_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:188</i> */
	public interface get_frame_count_callback extends Callback {
		int apply(cef_v8stack_trace_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:189</i> */
	public interface get_frame_callback extends Callback {
		cef_v8stack_frame_t apply(cef_v8stack_trace_t self, int index);
	};
	public cef_v8stack_trace_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "is_valid", "get_frame_count", "get_frame");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param is_valid C type : is_valid_callback*<br>
	 * @param get_frame_count C type : get_frame_count_callback*<br>
	 * @param get_frame C type : get_frame_callback*
	 */
	public cef_v8stack_trace_t(cef_base_t base, cef.cef_download_item_t.is_valid_callback is_valid, cef_v8stack_trace_t.get_frame_count_callback get_frame_count, cef_v8stack_trace_t.get_frame_callback get_frame) {
		super();
		this.base = base;
		this.is_valid = is_valid;
		this.get_frame_count = get_frame_count;
		this.get_frame = get_frame;
	}
	public cef_v8stack_trace_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_v8stack_trace_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_v8stack_trace_t implements Structure.ByValue {
		
	};
}
