package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_xml_reader_capi.h:75</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_xml_reader_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : move_to_next_node_callback* */
	public cef_xml_reader_t.move_to_next_node_callback move_to_next_node;
	/** C type : close_callback* */
	public cef.cef_zip_reader_t.close_callback close;
	/** C type : has_error_callback* */
	public cef_xml_reader_t.has_error_callback has_error;
	/** C type : get_depth_callback* */
	public cef_xml_reader_t.get_depth_callback get_depth;
	/** C type : is_empty_element_callback* */
	public cef_xml_reader_t.is_empty_element_callback is_empty_element;
	/** C type : has_value_callback* */
	public cef_xml_reader_t.has_value_callback has_value;
	/** C type : has_attributes_callback* */
	public cef_xml_reader_t.has_attributes_callback has_attributes;
	/** C type : get_attribute_count_callback* */
	public cef_xml_reader_t.get_attribute_count_callback get_attribute_count;
	/** C type : get_line_number_callback* */
	public cef_xml_reader_t.get_line_number_callback get_line_number;
	/** C type : move_to_attribute_byindex_callback* */
	public cef_xml_reader_t.move_to_attribute_byindex_callback move_to_attribute_byindex;
	/** C type : move_to_attribute_byqname_callback* */
	public cef_xml_reader_t.move_to_attribute_byqname_callback move_to_attribute_byqname;
	/** C type : move_to_attribute_bylname_callback* */
	public cef_xml_reader_t.move_to_attribute_bylname_callback move_to_attribute_bylname;
	/** C type : move_to_first_attribute_callback* */
	public cef_xml_reader_t.move_to_first_attribute_callback move_to_first_attribute;
	/** C type : move_to_next_attribute_callback* */
	public cef_xml_reader_t.move_to_next_attribute_callback move_to_next_attribute;
	/** C type : move_to_carrying_element_callback* */
	public cef_xml_reader_t.move_to_carrying_element_callback move_to_carrying_element;
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:46</i> */
	public interface move_to_next_node_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:47</i> */
	public interface close_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:48</i> */
	public interface has_error_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:49</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:50</i> */
	public interface cef_xml_node_type_t_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:51</i> */
	public interface get_depth_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:52</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:53</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:54</i> */
	public interface cef_string_userfree_t_callback4 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:55</i> */
	public interface cef_string_userfree_t_callback5 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:56</i> */
	public interface cef_string_userfree_t_callback6 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:57</i> */
	public interface cef_string_userfree_t_callback7 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:58</i> */
	public interface is_empty_element_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:59</i> */
	public interface has_value_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:60</i> */
	public interface cef_string_userfree_t_callback8 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:61</i> */
	public interface has_attributes_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:62</i> */
	public interface get_attribute_count_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:63</i> */
	public interface cef_string_userfree_t_callback9 extends Callback {
		int apply(cef_xml_reader_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:64</i> */
	public interface cef_string_userfree_t_callback10 extends Callback {
		int apply(cef_xml_reader_t self, cef_string_utf16_t qualifiedName);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:65</i> */
	public interface cef_string_userfree_t_callback11 extends Callback {
		int apply(cef_xml_reader_t self, cef_string_utf16_t localName, cef_string_utf16_t namespaceURI);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:66</i> */
	public interface cef_string_userfree_t_callback12 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:67</i> */
	public interface cef_string_userfree_t_callback13 extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:68</i> */
	public interface get_line_number_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:69</i> */
	public interface move_to_attribute_byindex_callback extends Callback {
		int apply(cef_xml_reader_t self, int index);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:70</i> */
	public interface move_to_attribute_byqname_callback extends Callback {
		int apply(cef_xml_reader_t self, cef_string_utf16_t qualifiedName);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:71</i> */
	public interface move_to_attribute_bylname_callback extends Callback {
		int apply(cef_xml_reader_t self, cef_string_utf16_t localName, cef_string_utf16_t namespaceURI);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:72</i> */
	public interface move_to_first_attribute_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:73</i> */
	public interface move_to_next_attribute_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	/** <i>native declaration : include\capi\cef_xml_reader_capi.h:74</i> */
	public interface move_to_carrying_element_callback extends Callback {
		int apply(cef_xml_reader_t self);
	};
	public cef_xml_reader_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "move_to_next_node", "close", "has_error", "get_depth", "is_empty_element", "has_value", "has_attributes", "get_attribute_count", "get_line_number", "move_to_attribute_byindex", "move_to_attribute_byqname", "move_to_attribute_bylname", "move_to_first_attribute", "move_to_next_attribute", "move_to_carrying_element");
	}
	public cef_xml_reader_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_xml_reader_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_xml_reader_t implements Structure.ByValue {
		
	};
}
