package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_callback_capi.h:12</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_completion_callback_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_complete_callback* */
	public cef.cef_delete_cookies_callback_t.on_complete_callback on_complete;
	/** <i>native declaration : include\capi\cef_callback_capi.h:11</i> */
	public interface on_complete_callback extends Callback {
		void apply(cef_completion_callback_t self);
	};
	public cef_completion_callback_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_complete");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_complete C type : on_complete_callback*
	 */
	public cef_completion_callback_t(cef_base_t base, cef.cef_delete_cookies_callback_t.on_complete_callback on_complete) {
		super();
		this.base = base;
		this.on_complete = on_complete;
	}
	public cef_completion_callback_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_completion_callback_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_completion_callback_t implements Structure.ByValue {
		
	};
}
