package cef;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\internal\cef_types.h:51</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_request_context_settings_t extends Structure {
	public int size;
	/** C type : cef_string_t */
	public cef_string_utf16_t cache_path;
	public int persist_session_cookies;
	public int persist_user_preferences;
	public int ignore_certificate_errors;
	/** C type : cef_string_t */
	public cef_string_utf16_t accept_language_list;
	public cef_request_context_settings_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("size", "cache_path", "persist_session_cookies", "persist_user_preferences", "ignore_certificate_errors", "accept_language_list");
	}
	/**
	 * @param cache_path C type : cef_string_t<br>
	 * @param accept_language_list C type : cef_string_t
	 */
	public cef_request_context_settings_t(int size, cef_string_utf16_t cache_path, int persist_session_cookies, int persist_user_preferences, int ignore_certificate_errors, cef_string_utf16_t accept_language_list) {
		super();
		this.size = size;
		this.cache_path = cache_path;
		this.persist_session_cookies = persist_session_cookies;
		this.persist_user_preferences = persist_user_preferences;
		this.ignore_certificate_errors = ignore_certificate_errors;
		this.accept_language_list = accept_language_list;
	}
	public cef_request_context_settings_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_request_context_settings_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_request_context_settings_t implements Structure.ByValue {
		
	};
}
