package cef;
import cef.CefLibrary._cef_command_line_t;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_app_capi.h:14</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_app_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : on_before_command_line_processing_callback* */
	public cef_app_t.on_before_command_line_processing_callback on_before_command_line_processing;
	/** C type : on_register_custom_schemes_callback* */
	public cef_app_t.on_register_custom_schemes_callback on_register_custom_schemes;
	/** C type : get_resource_bundle_handler_callback* */
	public cef_app_t.get_resource_bundle_handler_callback get_resource_bundle_handler;
	/** C type : get_browser_process_handler_callback* */
	public cef_app_t.get_browser_process_handler_callback get_browser_process_handler;
	/** C type : get_render_process_handler_callback* */
	public cef_app_t.get_render_process_handler_callback get_render_process_handler;
	/** <i>native declaration : include\capi\cef_app_capi.h:9</i> */
	public interface on_before_command_line_processing_callback extends Callback {
		void apply(cef_app_t self, cef_string_utf16_t process_type, _cef_command_line_t command_line);
	};
	/** <i>native declaration : include\capi\cef_app_capi.h:10</i> */
	public interface on_register_custom_schemes_callback extends Callback {
		void apply(cef_app_t self, cef_scheme_registrar_t registrar);
	};
	/** <i>native declaration : include\capi\cef_app_capi.h:11</i> */
	public interface get_resource_bundle_handler_callback extends Callback {
		cef_resource_bundle_handler_t apply(cef_app_t self);
	};
	/** <i>native declaration : include\capi\cef_app_capi.h:12</i> */
	public interface get_browser_process_handler_callback extends Callback {
		cef_browser_process_handler_t apply(cef_app_t self);
	};
	/** <i>native declaration : include\capi\cef_app_capi.h:13</i> */
	public interface get_render_process_handler_callback extends Callback {
		cef_render_process_handler_t apply(cef_app_t self);
	};
	public cef_app_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "on_before_command_line_processing", "on_register_custom_schemes", "get_resource_bundle_handler", "get_browser_process_handler", "get_render_process_handler");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param on_before_command_line_processing C type : on_before_command_line_processing_callback*<br>
	 * @param on_register_custom_schemes C type : on_register_custom_schemes_callback*<br>
	 * @param get_resource_bundle_handler C type : get_resource_bundle_handler_callback*<br>
	 * @param get_browser_process_handler C type : get_browser_process_handler_callback*<br>
	 * @param get_render_process_handler C type : get_render_process_handler_callback*
	 */
	public cef_app_t(cef_base_t base, cef_app_t.on_before_command_line_processing_callback on_before_command_line_processing, cef_app_t.on_register_custom_schemes_callback on_register_custom_schemes, cef_app_t.get_resource_bundle_handler_callback get_resource_bundle_handler, cef_app_t.get_browser_process_handler_callback get_browser_process_handler, cef_app_t.get_render_process_handler_callback get_render_process_handler) {
		super();
		this.base = base;
		this.on_before_command_line_processing = on_before_command_line_processing;
		this.on_register_custom_schemes = on_register_custom_schemes;
		this.get_resource_bundle_handler = get_resource_bundle_handler;
		this.get_browser_process_handler = get_browser_process_handler;
		this.get_render_process_handler = get_render_process_handler;
	}
	public cef_app_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_app_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_app_t implements Structure.ByValue {
		
	};
}
