package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_resource_bundle_capi.h:10</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_resource_bundle_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : get_data_resource_callback* */
	public cef_resource_bundle_t.get_data_resource_callback get_data_resource;
	/** C type : get_data_resource_for_scale_callback* */
	public cef_resource_bundle_t.get_data_resource_for_scale_callback get_data_resource_for_scale;
	/** <i>native declaration : include\capi\cef_resource_bundle_capi.h:7</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_resource_bundle_t self, int string_id);
	};
	/** <i>native declaration : include\capi\cef_resource_bundle_capi.h:8</i> */
	public interface get_data_resource_callback extends Callback {
		int apply(cef_resource_bundle_t self, int resource_id, PointerByReference data, IntByReference data_size);
	};
	/** <i>native declaration : include\capi\cef_resource_bundle_capi.h:9</i> */
	public interface get_data_resource_for_scale_callback extends Callback {
		int apply(cef_resource_bundle_t self, int resource_id, int scale_factor, PointerByReference data, IntByReference data_size);
	};
	public cef_resource_bundle_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "get_data_resource", "get_data_resource_for_scale");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param get_data_resource C type : get_data_resource_callback*<br>
	 * @param get_data_resource_for_scale C type : get_data_resource_for_scale_callback*
	 */
	public cef_resource_bundle_t(cef_base_t base, cef_resource_bundle_t.get_data_resource_callback get_data_resource, cef_resource_bundle_t.get_data_resource_for_scale_callback get_data_resource_for_scale) {
		super();
		this.base = base;
		this.get_data_resource = get_data_resource;
		this.get_data_resource_for_scale = get_data_resource_for_scale;
	}
	public cef_resource_bundle_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_resource_bundle_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_resource_bundle_t implements Structure.ByValue {
		
	};
}
