package cef;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\capi\cef_v8_capi.h:214</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cef_v8stack_frame_t extends Structure {
	/** C type : cef_base_t */
	public cef_base_t base;
	/** C type : is_valid_callback* */
	public cef.cef_download_item_t.is_valid_callback is_valid;
	/** C type : get_line_number_callback* */
	public cef.cef_xml_reader_t.get_line_number_callback get_line_number;
	/** C type : get_column_callback* */
	public cef_v8stack_frame_t.get_column_callback get_column;
	/** C type : is_eval_callback* */
	public cef_v8stack_frame_t.is_eval_callback is_eval;
	/** C type : is_constructor_callback* */
	public cef_v8stack_frame_t.is_constructor_callback is_constructor;
	/** <i>native declaration : include\capi\cef_v8_capi.h:206</i> */
	public interface is_valid_callback extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:207</i> */
	public interface cef_string_userfree_t_callback extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:208</i> */
	public interface cef_string_userfree_t_callback2 extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:209</i> */
	public interface cef_string_userfree_t_callback3 extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:210</i> */
	public interface get_line_number_callback extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:211</i> */
	public interface get_column_callback extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:212</i> */
	public interface is_eval_callback extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	/** <i>native declaration : include\capi\cef_v8_capi.h:213</i> */
	public interface is_constructor_callback extends Callback {
		int apply(cef_v8stack_frame_t self);
	};
	public cef_v8stack_frame_t() {
		super();
	}
	protected List <String> getFieldOrder() {
		return Arrays.asList("base", "is_valid", "get_line_number", "get_column", "is_eval", "is_constructor");
	}
	/**
	 * @param base C type : cef_base_t<br>
	 * @param is_valid C type : is_valid_callback*<br>
	 * @param get_line_number C type : get_line_number_callback*<br>
	 * @param get_column C type : get_column_callback*<br>
	 * @param is_eval C type : is_eval_callback*<br>
	 * @param is_constructor C type : is_constructor_callback*
	 */
	public cef_v8stack_frame_t(cef_base_t base, cef.cef_download_item_t.is_valid_callback is_valid, cef.cef_xml_reader_t.get_line_number_callback get_line_number, cef_v8stack_frame_t.get_column_callback get_column, cef_v8stack_frame_t.is_eval_callback is_eval, cef_v8stack_frame_t.is_constructor_callback is_constructor) {
		super();
		this.base = base;
		this.is_valid = is_valid;
		this.get_line_number = get_line_number;
		this.get_column = get_column;
		this.is_eval = is_eval;
		this.is_constructor = is_constructor;
	}
	public cef_v8stack_frame_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends cef_v8stack_frame_t implements Structure.ByReference {
		
	};
	public static class ByValue extends cef_v8stack_frame_t implements Structure.ByValue {
		
	};
}
